In [1]:
"""
S01 MPO training — integrate notebooks 01–07 mission context.

Scenario:
  - Same mission profile as notebook 07 baseline overflight (50-target meridian grid,
    seeded clouds over the corridor, dual camera, attitude safety on, image quality)
  - Controller features selected via ControllerFeatureConfig (see cell below)
  - MPO warmup (random + baseline) → 10 train episodes → eval
  - Preflight: inline feature checks + full ML training pytest suite

Verification: s01_utils/training_workflow.py
Artifacts: autonomous_control/models/nb-s01-08-<timestamp>/
Export: eval_best.mp4 in run directory
"""

'\nS01 MPO training — integrate notebooks 01–07 mission context.\n\nScenario:\n  - Same mission profile as notebook 07 baseline overflight (50-target meridian grid,\n    seeded clouds over the corridor, dual camera, attitude safety on, image quality)\n  - Controller features selected via ControllerFeatureConfig (see cell below)\n  - MPO warmup (random + baseline) → 10 train episodes → eval\n  - Preflight: inline feature checks + full ML training pytest suite\n\nVerification: s01_utils/training_workflow.py\nArtifacts: autonomous_control/models/nb-s01-08-<timestamp>/\nExport: eval_best.mp4 in run directory\n'

In [2]:
import os
import sys
from pathlib import Path

notebook_dir = Path.cwd()
backend_root = notebook_dir
for _ in range(6):
    if (backend_root / "simulation").is_dir():
        break
    backend_root = backend_root.parent
os.chdir(backend_root)
sys.path.insert(0, str(backend_root))
_s01_dir = backend_root / "notebooks" / "s01"
sys.path.insert(0, str(_s01_dir))
print(f"backend_root={backend_root}")

backend_root=d:\code\sem-proj-asc\backend

In [3]:
import importlib

import s01_utils.training_workflow as tw

importlib.reload(tw)

if tw.run_s01_training_preflight_gate():
    print("Training preflight gate passed (inline checks + pytest suite).")

c:\Users\cedri\miniconda3\envs\auto-sat\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Using device: cuda
Using device: cuda
Using device: cuda
Training preflight gate passed (inline checks + pytest suite).

In [4]:
from autonomous_control.feature_selection import ControllerFeatureConfig

# ── EDIT HERE: controller observation features ───────────────────────────────
# Keys must exist on SimulationTimestepState (see autonomous_control/feature_selection.py).
FEATURE_CONFIG = ControllerFeatureConfig(
    attitude_keys=(
        "body_z_angle_rad",
        "omega_sat_rad_s",
    ),
    orbit_keys=(
        "theta_orbit_rad",
    ),
    vision_keys=(
        "camera_observation_line_codes",
        "secondary_camera_observation_line_codes",
    ),
)

WORKFLOW_CONFIG = tw.TrainingWorkflowConfig(
    seed=7,
    train_episodes=100,
    feature_config=FEATURE_CONFIG,
)

# Resolve secondary camera bin count for layout tables (same mission profile as training).
_secondary_bins = int(
    tw.build_s01_training_mission_setup(seed=WORKFLOW_CONFIG.seed)
    .resolve(require_camera=True)
    .secondary_camera_observation_line_n_bins
)
tw.display_feature_tables(FEATURE_CONFIG, secondary_camera_bins=_secondary_bins)

### Controller feature selection (`ControllerFeatureConfig`)

Edit `FEATURE_CONFIG` in the notebook cell below, or change `S01_TRAINING_FEATURE_CONFIG` in `s01_utils/training_workflow.py`.

,group,timestep_key,state_dims,unit,encoder_path,source_module
0,attitude,body_z_angle_rad,1,rad,scalar → MLP branch,autonomous_control/feature_selection.py
1,attitude,omega_sat_rad_s,1,rad/s,scalar → MLP branch,autonomous_control/feature_selection.py
2,orbit,theta_orbit_rad,1,rad,scalar → MLP branch,autonomous_control/feature_selection.py
3,vision,camera_observation_line_codes,100,obs code / bin,int8 codes → embed → 1D-CNN,autonomous_control/feature_selection.py
4,vision,secondary_camera_observation_line_codes,200,obs code / bin,int8 codes → embed → 1D-CNN,autonomous_control/feature_selection.py

### Controller encoder routing (scalar **3**, vision streams **2**)

,stage,inputs,input_shape,module
0,scalar branch,"body_z_angle_rad, omega_sat_rad_s, theta_orbit...","(3,) float32",MLP → 90-D
1,vision branch (primary (nadir)),camera_observation_line_codes,"(100,) int8",ObservationLineCNNEncoder → 32-D
2,vision branch (secondary (forward)),secondary_camera_observation_line_codes,"(200,) int8",ObservationLineCNNEncoder → 32-D
3,vision fusion,concat CNN embeddings,"(64,)",MLP → 90-D
4,policy / Q trunk,"concat(scalar, vision)","(180,)",Actor head / Critic head

### Observation code legend (vision line bins)

   code         label
0   -99  not_computed
1     0         space
2     1         earth
3     2         cloud
4     3        target

In [5]:
setup = tw.build_training_workflow_setup(WORKFLOW_CONFIG)
tw.print_training_setup_summary(setup)
tw.display_feature_snapshot_tables(setup)

Using device: cuda
S01 MPO training setup (notebook 07 baseline overflight profile)
  run_dir:           D:\code\sem-proj-asc\backend\autonomous_control\models\nb-s01-08-2026-06-24_23-16-21
  seed:              7
  altitude:          528.8 km
  targets:           50
  clouds:            25 (seeded over target corridor)
  orbit window:      -32.7° .. 37.1°
  episode steps:     2904
  attitude safety:   on (training_episode_simulation_config)
  scalar dim:        3
  vision streams:    [('camera_observation_line_codes', 100), ('secondary_camera_observation_line_codes', 200)]
  encoder trunk:     180-D
  secondary bins:    200
  feature keys:      ['body_z_angle_rad', 'omega_sat_rad_s', 'theta_orbit_rad', 'camera_observation_line_codes', 'secondary_camera_observation_line_codes']
  warmup episodes:   4
  train episodes:    100
  eval episodes:     2
  MPO batch_size:    256
  MPO gamma:         0.99
  MPO LRs q/pi/eta:  0.00045/0.00015/0.001
  target_kl mu/sigma: 0.1/0.0001
  reward flags:      distance_reward, outer_gate

d:\code\sem-proj-asc\backend\simulation\stepper.py:171: UserWarning: controller_update_interval (1 s) is not an integer multiple of simulation_timestep (0.4 s); using nearest multiple: 0.8 s (2 sim steps).
  self._controller_interval_steps, self._effective_controller_interval_s = resolve_controller_interval_steps(

### Scalar features at episode start (MLP branch)

   scalar_index     group      timestep_key     value   unit
0             0  attitude  body_z_angle_rad  4.111343    rad
1             1  attitude   omega_sat_rad_s  0.000000  rad/s
2             2     orbit   theta_orbit_rad  0.969750    rad

### Vision line features at episode start (CNN branches)

,camera,timestep_key,n_bins,preview,dominant_code,target_bins
0,primary (nadir),camera_observation_line_codes,100,"[1, 1, 1, 1, 1, 1, 1, 1, …]",1 (earth),0
1,secondary (forward),secondary_camera_observation_line_codes,200,"[1, 1, 1, 1, 1, 1, 1, 1, …]",1 (earth),0

Structured `ControllerObservation`: scalars **3**, vision **camera_observation_line_codes 100 bins, secondary_camera_observation_line_codes 200 bins** → encoder trunk **180**-D.

In [6]:
result = tw.run_training_workflow(setup, show_progress=True)

Warmup:   0%|          | 0/4 [00:00<?, ?ep/s]

╭──────────────────────────────────────────────── Simulation info ────────────────────────────────────────────────╮
│  Parameter                                     Value                                                            │
│  episode duration                              1160.93 s                                                        │
│  simulation timestep                           0.399906 s                                                       │
│  integration steps                             2903 (+1 state samples)                                          │
│  orbit altitude                                528.76 km                                                        │
│  orbit period                                  5703.8 s                                                         │
│  theta center offset                           90.00 deg                                                        │
│  episode theta start (rel. center)             -32.693 deg                                                      │
│  episode theta end (rel. center)               37.091 deg                                                       │
│  sat motion span scale                         1.050                                                            │
│  sat z offset                                  0.00 deg                                                         │
│  target areas                                  50                                                               │
│  target phi stripe                             79.93 deg .. 104.46 deg                                          │
│  cloud patches                                 25                                                               │
│  render mode                                   headless                                                         │
│  torque command source                         external                                                         │
│  torque policy                                 MPOAgent:warmup                                                  │
│  attitude controller                           enabled                                                          │
│  control stack (display)                       MPOAgent:warmup · attitude_controller                            │
│  controller seed                               -                                                                │
│  controller update (configured)                1 s                                                              │
│  controller update (effective)                 0.8 s (2 steps)                                                  │
│  reaction-wheel torque max                     0.1000 N*m                                                       │
│  attitude safety cutoff                        |omega_sat| > 3.00 deg/s -> block opposing torque                │
│  camera kernel backend                         accelerated                                                      │
│  reward shaping                                distance_reward, outer_gate                                      │
│  episode runner mode                           warmup                                                           │
│  agent                                         MPOAgent                                                         │
│  Camera 1 (primary) - role                     shapes reward (observation line + strip)                         │
│  Camera 1 (primary) - tilt off nadir           0.00 deg                                                         │
│  Camera 1 (primary) - FOV (cross x along)      1.61 deg x 1.20 deg                                              │
│  Camera 1 (primary) - resolution               9344 x 7000 px                                                   │
│  Camera 1 (primary) - pixel pitch              3.20 um                                                          │
│  Camera 1 (primary) - focal length             1067.0 mm                                                        │
│  Camera 1 (primary) - GSD @ 528.8 km           1.586 m                                                          │
│  Camera 1 (primary) - observation line bins    100                                                              │
│  Camera 1 (primary) - strip ray samples        96                                                               │
│  Camera 1 (primary) - sim vertical FOV         1.203 deg                                                        │
│  Camera 1 (primary) - exposure time            100 us (image smear)                                             │
│  Camera 2 (secondary) - role                   cloud/context only (no exposure in reward)                       │
│  Camera 2 (secondary) - tilt off nadir         25.00 deg                                                        │
│  Camera 2 (secondary) - FOV (cross x along)    102.45 deg x 70.00 deg                                           │
│  Camera 2 (secondary) - resolution             5312 x 2988 px                                                   │
│  Camera 2 (secondary) - pixel pitch            1.55 um                                                          │
│  Camera 2 (secondary) - focal length           3.3 mm                                                           │
│  Camera 2 (secondary) - GSD @ 528.8 km         247.818 m                                                        │
│  Camera 2 (secondary) - observation line bins  200                                                              │
│  Camera 2 (secondary) - sim vertical FOV       70.000 deg                                                       │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 1 / 4                                                                           │
│  step            400 / 2903 (13.8%)                                                                        │
│  sim time        160.0 s                                                                                   │
│  step reward     -100.0000                                                                                 │
│  episode return  -40000.00                                                                                 │
│  body z angle    -2.1087 rad                                                                               │
│  omega sat       -0.0039 rad/s                                                                             │
│  image smear     0.612 px                                                                                  │
│  image quality   0.2350                                                                                    │
│  buffer          399                                                                                       │
│  agent steps     399                                                                                       │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 1 / 4                                                                           │
│  step            800 / 2903 (27.6%)                                                                        │
│  sim time        319.9 s                                                                                   │
│  step reward     -100.0000                                                                                 │
│  episode return  -80000.00                                                                                 │
│  body z angle    -1.8231 rad                                                                               │
│  omega sat       -0.0028 rad/s                                                                             │
│  image smear     0.575 px                                                                                  │
│  image quality   0.2475                                                                                    │
│  buffer          799                                                                                       │
│  agent steps     799                                                                                       │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 1 / 4                                                                           │
│  step            1200 / 2903 (41.3%)                                                                       │
│  sim time        479.9 s                                                                                   │
│  step reward     -100.0000                                                                                 │
│  episode return  -109400.00                                                                                │
│  body z angle    -1.6437 rad                                                                               │
│  omega sat       0.0014 rad/s                                                                              │
│  image smear     0.432 px                                                                                  │
│  image quality   0.3044                                                                                    │
│  buffer          1199                                                                                      │
│  agent steps     1199                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 1 / 4                                                                           │
│  step            1600 / 2903 (55.1%)                                                                       │
│  sim time        639.9 s                                                                                   │
│  step reward     -12.7490                                                                                  │
│  episode return  -145600.26                                                                                │
│  body z angle    -1.4514 rad                                                                               │
│  omega sat       -0.0039 rad/s                                                                             │
│  image smear     0.611 px                                                                                  │
│  image quality   0.2363                                                                                    │
│  buffer          1599                                                                                      │
│  agent steps     1599                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 1 / 4                                                                           │
│  step            2000 / 2903 (68.9%)                                                                       │
│  sim time        799.8 s                                                                                   │
│  step reward     -100.0000                                                                                 │
│  episode return  -180475.79                                                                                │
│  body z angle    -1.2915 rad                                                                               │
│  omega sat       0.0015 rad/s                                                                              │
│  image smear     0.427 px                                                                                  │
│  image quality   0.3072                                                                                    │
│  buffer          1999                                                                                      │
│  agent steps     1999                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 1 / 4                                                                           │
│  step            2400 / 2903 (82.7%)                                                                       │
│  sim time        959.8 s                                                                                   │
│  step reward     -100.0000                                                                                 │
│  episode return  -220475.79                                                                                │
│  body z angle    -1.1461 rad                                                                               │
│  omega sat       -0.0002 rad/s                                                                             │
│  image smear     0.486 px                                                                                  │
│  image quality   0.2801                                                                                    │
│  buffer          2399                                                                                      │
│  agent steps     2399                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 1 / 4                                                                           │
│  step            2800 / 2903 (96.5%)                                                                       │
│  sim time        1119.7 s                                                                                  │
│  step reward     -100.0000                                                                                 │
│  episode return  -260475.79                                                                                │
│  body z angle    -0.9586 rad                                                                               │
│  omega sat       0.0018 rad/s                                                                              │
│  image smear     0.417 px                                                                                  │
│  image quality   0.3120                                                                                    │
│  buffer          2799                                                                                      │
│  agent steps     2799                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 1 / 4                                                                           │
│  step            2903 / 2903 (100.0%)                                                                      │
│  sim time        1160.9 s                                                                                  │
│  step reward     -100.0000                                                                                 │
│  episode return  -270775.79                                                                                │
│  body z angle    -0.6095 rad                                                                               │
│  omega sat       0.0195 rad/s                                                                              │
│  image smear     0.231 px                                                                                  │
│  image quality   0.4405                                                                                    │
│  buffer          2902                                                                                      │
│  agent steps     2902                                                                                      │
│  status          episode done                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

warmup ep 1: 100%|██████████| 2903/2903 [01:18<00:00, 37.19step/s, reward=-100.000, total=-270775.8]

Warmup:  25%|██▌       | 1/4 [01:18<03:54, 78.09s/ep]

[run_serial] end mode=warmup steps=2903 total_reward=-270775.792411 avg_reward=-93.274472

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 2 / 4                                                                           │
│  step            400 / 2903 (13.8%)                                                                        │
│  sim time        160.0 s                                                                                   │
│  step reward     -100.0000                                                                                 │
│  episode return  -40000.00                                                                                 │
│  body z angle    -2.0257 rad                                                                               │
│  omega sat       -0.0017 rad/s                                                                             │
│  image smear     0.537 px                                                                                  │
│  image quality   0.2606                                                                                    │
│  buffer          3302                                                                                      │
│  agent steps     3302                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 2 / 4                                                                           │
│  step            800 / 2903 (27.6%)                                                                        │
│  sim time        319.9 s                                                                                   │
│  step reward     -100.0000                                                                                 │
│  episode return  -80000.00                                                                                 │
│  body z angle    -1.8774 rad                                                                               │
│  omega sat       -0.0029 rad/s                                                                             │
│  image smear     0.579 px                                                                                  │
│  image quality   0.2460                                                                                    │
│  buffer          3702                                                                                      │
│  agent steps     3702                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 2 / 4                                                                           │
│  step            1200 / 2903 (41.3%)                                                                       │
│  sim time        479.9 s                                                                                   │
│  step reward     -100.0000                                                                                 │
│  episode return  -108700.00                                                                                │
│  body z angle    -1.8340 rad                                                                               │
│  omega sat       0.0012 rad/s                                                                              │
│  image smear     0.431 px                                                                                  │
│  image quality   0.3010                                                                                    │
│  buffer          4102                                                                                      │
│  agent steps     4102                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 2 / 4                                                                           │
│  step            1600 / 2903 (55.1%)                                                                       │
│  sim time        639.9 s                                                                                   │
│  step reward     -100.0000                                                                                 │
│  episode return  -133814.67                                                                                │
│  body z angle    -1.5162 rad                                                                               │
│  omega sat       -0.0004 rad/s                                                                             │
│  image smear     0.494 px                                                                                  │
│  image quality   0.2767                                                                                    │
│  buffer          4502                                                                                      │
│  agent steps     4502                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 2 / 4                                                                           │
│  step            2000 / 2903 (68.9%)                                                                       │
│  sim time        799.8 s                                                                                   │
│  step reward     -100.0000                                                                                 │
│  episode return  -167784.70                                                                                │
│  body z angle    -1.3677 rad                                                                               │
│  omega sat       0.0026 rad/s                                                                              │
│  image smear     0.390 px                                                                                  │
│  image quality   0.3262                                                                                    │
│  buffer          4902                                                                                      │
│  agent steps     4902                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 2 / 4                                                                           │
│  step            2400 / 2903 (82.7%)                                                                       │
│  sim time        959.8 s                                                                                   │
│  step reward     -100.0000                                                                                 │
│  episode return  -207784.70                                                                                │
│  body z angle    -1.0875 rad                                                                               │
│  omega sat       -0.0017 rad/s                                                                             │
│  image smear     0.538 px                                                                                  │
│  image quality   0.2600                                                                                    │
│  buffer          5302                                                                                      │
│  agent steps     5302                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 2 / 4                                                                           │
│  step            2800 / 2903 (96.5%)                                                                       │
│  sim time        1119.7 s                                                                                  │
│  step reward     -100.0000                                                                                 │
│  episode return  -247784.70                                                                                │
│  body z angle    -1.6493 rad                                                                               │
│  omega sat       0.0242 rad/s                                                                              │
│  image smear     0.800 px                                                                                  │
│  image quality   0.1519                                                                                    │
│  buffer          5702                                                                                      │
│  agent steps     5702                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 2 / 4                                                                           │
│  step            2903 / 2903 (100.0%)                                                                      │
│  sim time        1160.9 s                                                                                  │
│  step reward     -100.0000                                                                                 │
│  episode return  -258084.70                                                                                │
│  body z angle    -0.8946 rad                                                                               │
│  omega sat       0.0020 rad/s                                                                              │
│  image smear     0.412 px                                                                                  │
│  image quality   0.3146                                                                                    │
│  buffer          5805                                                                                      │
│  agent steps     5805                                                                                      │
│  status          episode done                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

warmup ep 2: 100%|██████████| 2903/2903 [01:19<00:00, 36.60step/s, reward=-100.000, total=-258084.7]

Warmup:  50%|█████     | 2/4 [02:37<02:37, 78.84s/ep]

[run_serial] end mode=warmup steps=2903 total_reward=-258084.696795 avg_reward=-88.902755

╭──────────────────────────────────────────────── Simulation info ────────────────────────────────────────────────╮
│  Parameter                                     Value                                                            │
│  episode duration                              1160.93 s                                                        │
│  simulation timestep                           0.399906 s                                                       │
│  integration steps                             2903 (+1 state samples)                                          │
│  orbit altitude                                528.76 km                                                        │
│  orbit period                                  5703.8 s                                                         │
│  theta center offset                           90.00 deg                                                        │
│  episode theta start (rel. center)             -32.693 deg                                                      │
│  episode theta end (rel. center)               37.091 deg                                                       │
│  sat motion span scale                         1.050                                                            │
│  sat z offset                                  0.00 deg                                                         │
│  target areas                                  50                                                               │
│  target phi stripe                             79.93 deg .. 104.46 deg                                          │
│  cloud patches                                 25                                                               │
│  render mode                                   headless                                                         │
│  torque command source                         external                                                         │
│  torque policy                                 MPOAgent:warmup                                                  │
│  attitude controller                           enabled                                                          │
│  control stack (display)                       MPOAgent:warmup · attitude_controller                            │
│  controller seed                               -                                                                │
│  controller update (configured)                1 s                                                              │
│  controller update (effective)                 0.8 s (2 steps)                                                  │
│  reaction-wheel torque max                     0.1000 N*m                                                       │
│  attitude safety cutoff                        |omega_sat| > 3.00 deg/s -> block opposing torque                │
│  camera kernel backend                         accelerated                                                      │
│  reward shaping                                distance_reward, outer_gate                                      │
│  episode runner mode                           warmup                                                           │
│  agent                                         MPOAgent                                                         │
│  Camera 1 (primary) - role                     shapes reward (observation line + strip)                         │
│  Camera 1 (primary) - tilt off nadir           0.00 deg                                                         │
│  Camera 1 (primary) - FOV (cross x along)      1.61 deg x 1.20 deg                                              │
│  Camera 1 (primary) - resolution               9344 x 7000 px                                                   │
│  Camera 1 (primary) - pixel pitch              3.20 um                                                          │
│  Camera 1 (primary) - focal length             1067.0 mm                                                        │
│  Camera 1 (primary) - GSD @ 528.8 km           1.586 m                                                          │
│  Camera 1 (primary) - observation line bins    100                                                              │
│  Camera 1 (primary) - strip ray samples        96                                                               │
│  Camera 1 (primary) - sim vertical FOV         1.203 deg                                                        │
│  Camera 1 (primary) - exposure time            100 us (image smear)                                             │
│  Camera 2 (secondary) - role                   cloud/context only (no exposure in reward)                       │
│  Camera 2 (secondary) - tilt off nadir         25.00 deg                                                        │
│  Camera 2 (secondary) - FOV (cross x along)    102.45 deg x 70.00 deg                                           │
│  Camera 2 (secondary) - resolution             5312 x 2988 px                                                   │
│  Camera 2 (secondary) - pixel pitch            1.55 um                                                          │
│  Camera 2 (secondary) - focal length           3.3 mm                                                           │
│  Camera 2 (secondary) - GSD @ 528.8 km         247.818 m                                                        │
│  Camera 2 (secondary) - observation line bins  200                                                              │
│  Camera 2 (secondary) - sim vertical FOV       70.000 deg                                                       │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 3 / 4                                                                           │
│  step            400 / 2903 (13.8%)                                                                        │
│  sim time        160.0 s                                                                                   │
│  step reward     -100.0000                                                                                 │
│  episode return  -40000.00                                                                                 │
│  body z angle    -1.9957 rad                                                                               │
│  omega sat       0.0012 rad/s                                                                              │
│  image smear     0.437 px                                                                                  │
│  image quality   0.3019                                                                                    │
│  buffer          6205                                                                                      │
│  agent steps     6205                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 3 / 4                                                                           │
│  step            800 / 2903 (27.6%)                                                                        │
│  sim time        319.9 s                                                                                   │
│  step reward     -100.0000                                                                                 │
│  episode return  -80000.00                                                                                 │
│  body z angle    -1.7661 rad                                                                               │
│  omega sat       -0.0052 rad/s                                                                             │
│  image smear     0.658 px                                                                                  │
│  image quality   0.2231                                                                                    │
│  buffer          6605                                                                                      │
│  agent steps     6605                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 3 / 4                                                                           │
│  step            1200 / 2903 (41.3%)                                                                       │
│  sim time        479.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  -106600.00                                                                                │
│  body z angle    -2.4586 rad                                                                               │
│  omega sat       -0.0033 rad/s                                                                             │
│  image smear     0.564 px                                                                                  │
│  image quality   0.1869                                                                                    │
│  buffer          7005                                                                                      │
│  agent steps     7005                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 3 / 4                                                                           │
│  step            1600 / 2903 (55.1%)                                                                       │
│  sim time        639.9 s                                                                                   │
│  step reward     -12.7490                                                                                  │
│  episode return  -134717.85                                                                                │
│  body z angle    -1.4668 rad                                                                               │
│  omega sat       0.0012 rad/s                                                                              │
│  image smear     0.438 px                                                                                  │
│  image quality   0.3015                                                                                    │
│  buffer          7405                                                                                      │
│  agent steps     7405                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 3 / 4                                                                           │
│  step            2000 / 2903 (68.9%)                                                                       │
│  sim time        799.8 s                                                                                   │
│  step reward     -100.0000                                                                                 │
│  episode return  -168472.70                                                                                │
│  body z angle    -1.2465 rad                                                                               │
│  omega sat       -0.0055 rad/s                                                                             │
│  image smear     0.667 px                                                                                  │
│  image quality   0.2207                                                                                    │
│  buffer          7805                                                                                      │
│  agent steps     7805                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 3 / 4                                                                           │
│  step            2400 / 2903 (82.7%)                                                                       │
│  sim time        959.8 s                                                                                   │
│  step reward     -100.0000                                                                                 │
│  episode return  -208472.70                                                                                │
│  body z angle    -1.9035 rad                                                                               │
│  omega sat       -0.0049 rad/s                                                                             │
│  image smear     0.640 px                                                                                  │
│  image quality   0.1723                                                                                    │
│  buffer          8205                                                                                      │
│  agent steps     8205                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 3 / 4                                                                           │
│  step            2800 / 2903 (96.5%)                                                                       │
│  sim time        1119.7 s                                                                                  │
│  step reward     -100.0000                                                                                 │
│  episode return  -248472.70                                                                                │
│  body z angle    -0.9380 rad                                                                               │
│  omega sat       0.0012 rad/s                                                                              │
│  image smear     0.439 px                                                                                  │
│  image quality   0.3010                                                                                    │
│  buffer          8605                                                                                      │
│  agent steps     8605                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 3 / 4                                                                           │
│  step            2903 / 2903 (100.0%)                                                                      │
│  sim time        1160.9 s                                                                                  │
│  step reward     -100.0000                                                                                 │
│  episode return  -258772.70                                                                                │
│  body z angle    -0.7334 rad                                                                               │
│  omega sat       -0.0034 rad/s                                                                             │
│  image smear     0.591 px                                                                                  │
│  image quality   0.2400                                                                                    │
│  buffer          8708                                                                                      │
│  agent steps     8708                                                                                      │
│  status          episode done                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

warmup ep 3: 100%|██████████| 2903/2903 [01:20<00:00, 36.20step/s, reward=-100.000, total=-258772.7]

Warmup:  75%|███████▌  | 3/4 [03:57<01:19, 79.48s/ep]

[run_serial] end mode=warmup steps=2903 total_reward=-258772.704243 avg_reward=-89.139753

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 4 / 4                                                                           │
│  step            400 / 2903 (13.8%)                                                                        │
│  sim time        160.0 s                                                                                   │
│  step reward     -100.0000                                                                                 │
│  episode return  -40000.00                                                                                 │
│  body z angle    -1.9957 rad                                                                               │
│  omega sat       0.0012 rad/s                                                                              │
│  image smear     0.437 px                                                                                  │
│  image quality   0.3019                                                                                    │
│  buffer          9108                                                                                      │
│  agent steps     9108                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 4 / 4                                                                           │
│  step            800 / 2903 (27.6%)                                                                        │
│  sim time        319.9 s                                                                                   │
│  step reward     -100.0000                                                                                 │
│  episode return  -80000.00                                                                                 │
│  body z angle    -1.7661 rad                                                                               │
│  omega sat       -0.0052 rad/s                                                                             │
│  image smear     0.658 px                                                                                  │
│  image quality   0.2231                                                                                    │
│  buffer          9508                                                                                      │
│  agent steps     9508                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 4 / 4                                                                           │
│  step            1200 / 2903 (41.3%)                                                                       │
│  sim time        479.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  -106600.00                                                                                │
│  body z angle    -2.4586 rad                                                                               │
│  omega sat       -0.0033 rad/s                                                                             │
│  image smear     0.564 px                                                                                  │
│  image quality   0.1869                                                                                    │
│  buffer          9908                                                                                      │
│  agent steps     9908                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 4 / 4                                                                           │
│  step            1600 / 2903 (55.1%)                                                                       │
│  sim time        639.9 s                                                                                   │
│  step reward     -12.7490                                                                                  │
│  episode return  -134717.85                                                                                │
│  body z angle    -1.4668 rad                                                                               │
│  omega sat       0.0012 rad/s                                                                              │
│  image smear     0.438 px                                                                                  │
│  image quality   0.3015                                                                                    │
│  buffer          10308                                                                                     │
│  agent steps     10308                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 4 / 4                                                                           │
│  step            2000 / 2903 (68.9%)                                                                       │
│  sim time        799.8 s                                                                                   │
│  step reward     -100.0000                                                                                 │
│  episode return  -168472.70                                                                                │
│  body z angle    -1.2465 rad                                                                               │
│  omega sat       -0.0055 rad/s                                                                             │
│  image smear     0.667 px                                                                                  │
│  image quality   0.2207                                                                                    │
│  buffer          10708                                                                                     │
│  agent steps     10708                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 4 / 4                                                                           │
│  step            2400 / 2903 (82.7%)                                                                       │
│  sim time        959.8 s                                                                                   │
│  step reward     -100.0000                                                                                 │
│  episode return  -208472.70                                                                                │
│  body z angle    -1.9035 rad                                                                               │
│  omega sat       -0.0049 rad/s                                                                             │
│  image smear     0.640 px                                                                                  │
│  image quality   0.1723                                                                                    │
│  buffer          11108                                                                                     │
│  agent steps     11108                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 4 / 4                                                                           │
│  step            2800 / 2903 (96.5%)                                                                       │
│  sim time        1119.7 s                                                                                  │
│  step reward     -100.0000                                                                                 │
│  episode return  -248472.70                                                                                │
│  body z angle    -0.9380 rad                                                                               │
│  omega sat       0.0012 rad/s                                                                              │
│  image smear     0.439 px                                                                                  │
│  image quality   0.3010                                                                                    │
│  buffer          11508                                                                                     │
│  agent steps     11508                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 4 / 4                                                                           │
│  step            2903 / 2903 (100.0%)                                                                      │
│  sim time        1160.9 s                                                                                  │
│  step reward     -100.0000                                                                                 │
│  episode return  -258772.70                                                                                │
│  body z angle    -0.7334 rad                                                                               │
│  omega sat       -0.0034 rad/s                                                                             │
│  image smear     0.591 px                                                                                  │
│  image quality   0.2400                                                                                    │
│  buffer          11611                                                                                     │
│  agent steps     11611                                                                                     │
│  status          episode done                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

warmup ep 4: 100%|██████████| 2903/2903 [01:19<00:00, 36.72step/s, reward=-100.000, total=-258772.7]

Warmup: 100%|██████████| 4/4 [05:16<00:00, 79.20s/ep]

[run_serial] end mode=warmup steps=2903 total_reward=-258772.704243 avg_reward=-89.139753

Train:   0%|          | 0/100 [00:00<?, ?ep/s]

╭──────────────────────────────────────────────── Simulation info ────────────────────────────────────────────────╮
│  Parameter                                     Value                                                            │
│  episode duration                              1160.93 s                                                        │
│  simulation timestep                           0.399906 s                                                       │
│  integration steps                             2903 (+1 state samples)                                          │
│  orbit altitude                                528.76 km                                                        │
│  orbit period                                  5703.8 s                                                         │
│  theta center offset                           90.00 deg                                                        │
│  episode theta start (rel. center)             -32.693 deg                                                      │
│  episode theta end (rel. center)               37.091 deg                                                       │
│  sat motion span scale                         1.050                                                            │
│  sat z offset                                  0.00 deg                                                         │
│  target areas                                  50                                                               │
│  target phi stripe                             79.93 deg .. 104.46 deg                                          │
│  cloud patches                                 25                                                               │
│  render mode                                   headless                                                         │
│  torque command source                         external                                                         │
│  torque policy                                 MPOAgent:train                                                   │
│  attitude controller                           enabled                                                          │
│  control stack (display)                       MPOAgent:train · attitude_controller                             │
│  controller seed                               -                                                                │
│  controller update (configured)                1 s                                                              │
│  controller update (effective)                 0.8 s (2 steps)                                                  │
│  reaction-wheel torque max                     0.1000 N*m                                                       │
│  attitude safety cutoff                        |omega_sat| > 3.00 deg/s -> block opposing torque                │
│  camera kernel backend                         accelerated                                                      │
│  reward shaping                                distance_reward, outer_gate                                      │
│  episode runner mode                           train                                                            │
│  agent                                         MPOAgent                                                         │
│  Camera 1 (primary) - role                     shapes reward (observation line + strip)                         │
│  Camera 1 (primary) - tilt off nadir           0.00 deg                                                         │
│  Camera 1 (primary) - FOV (cross x along)      1.61 deg x 1.20 deg                                              │
│  Camera 1 (primary) - resolution               9344 x 7000 px                                                   │
│  Camera 1 (primary) - pixel pitch              3.20 um                                                          │
│  Camera 1 (primary) - focal length             1067.0 mm                                                        │
│  Camera 1 (primary) - GSD @ 528.8 km           1.586 m                                                          │
│  Camera 1 (primary) - observation line bins    100                                                              │
│  Camera 1 (primary) - strip ray samples        96                                                               │
│  Camera 1 (primary) - sim vertical FOV         1.203 deg                                                        │
│  Camera 1 (primary) - exposure time            100 us (image smear)                                             │
│  Camera 2 (secondary) - role                   cloud/context only (no exposure in reward)                       │
│  Camera 2 (secondary) - tilt off nadir         25.00 deg                                                        │
│  Camera 2 (secondary) - FOV (cross x along)    102.45 deg x 70.00 deg                                           │
│  Camera 2 (secondary) - resolution             5312 x 2988 px                                                   │
│  Camera 2 (secondary) - pixel pitch            1.55 um                                                          │
│  Camera 2 (secondary) - focal length           3.3 mm                                                           │
│  Camera 2 (secondary) - GSD @ 528.8 km         247.818 m                                                        │
│  Camera 2 (secondary) - observation line bins  200                                                              │
│  Camera 2 (secondary) - sim vertical FOV       70.000 deg                                                       │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 100                                                                       │
│  step               23 / 2903 (0.8%)                                                                       │
│  sim time           9.2 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -2300.00                                                                               │
│  body z angle       -2.1163 rad                                                                            │
│  omega sat          0.0174 rad/s                                                                           │
│  image smear        0.112 px                                                                               │
│  image quality      0.6285                                                                                 │
│  buffer             11634                                                                                  │
│  agent steps        11634                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       3.618673                                                                               │
│  q loss (ep mean)   17496.587891                                                                           │
│  pi loss (ep mean)  -0.125119                                                                              │
│  eta (ep mean)      2.743424                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 1:   1%|          | 23/2903 [00:02<04:44, 10.13step/s, reward=-100.000, total=-2300.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 23/2903 (mode=train)
  return setup.runner.run_serial(
Train:   1%|          | 1/100 [00:02<03:49,  2.31s/ep, kl=3.8925, reward=-2300.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 23/2903 (mode=train)
[run_serial] end mode=train steps=23 total_reward=-2300.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 100                                                                       │
│  step               25 / 2903 (0.9%)                                                                       │
│  sim time           10.0 s                                                                                 │
│  step reward        -100.0000                                                                              │
│  episode return     -2500.00                                                                               │
│  body z angle       -2.0093 rad                                                                            │
│  omega sat          0.0316 rad/s                                                                           │
│  image smear        0.610 px                                                                               │
│  image quality      0.2346                                                                                 │
│  buffer             11659                                                                                  │
│  agent steps        11659                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       936.778412                                                                             │
│  q loss (ep mean)   11447.412821                                                                           │
│  pi loss (ep mean)  -0.328380                                                                              │
│  eta (ep mean)      2.814701                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 2:   1%|          | 25/2903 [00:02<04:53,  9.81step/s, reward=-100.000, total=-2500.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 25/2903 (mode=train)
  return setup.runner.run_serial(
Train:   2%|▏         | 2/100 [00:04<04:02,  2.47s/ep, kl=1181.4413, reward=-2500.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 25/2903 (mode=train)
[run_serial] end mode=train steps=25 total_reward=-2500.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 100                                                                       │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0880 rad                                                                            │
│  omega sat          0.0225 rad/s                                                                           │
│  image smear        0.286 px                                                                               │
│  image quality      0.3973                                                                                 │
│  buffer             11678                                                                                  │
│  agent steps        11678                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       17357.481066                                                                           │
│  q loss (ep mean)   2009.922323                                                                            │
│  pi loss (ep mean)  -0.544935                                                                              │
│  eta (ep mean)      2.901145                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 3:   1%|          | 19/2903 [00:02<05:04,  9.47step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:   3%|▎         | 3/100 [00:06<03:41,  2.28s/ep, kl=17776.5443, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 4 / 100                                                                       │
│  step               27 / 2903 (0.9%)                                                                       │
│  sim time           10.8 s                                                                                 │
│  step reward        -100.0000                                                                              │
│  episode return     -2700.00                                                                               │
│  body z angle       -1.9781 rad                                                                            │
│  omega sat          0.0346 rad/s                                                                           │
│  image smear        0.722 px                                                                               │
│  image quality      0.2050                                                                                 │
│  buffer             11705                                                                                  │
│  agent steps        11705                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       34811.532227                                                                           │
│  q loss (ep mean)   1201.049974                                                                            │
│  pi loss (ep mean)  -0.616906                                                                              │
│  eta (ep mean)      3.018441                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 4:   1%|          | 27/2903 [00:02<04:57,  9.67step/s, reward=-100.000, total=-2700.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 27/2903 (mode=train)
  return setup.runner.run_serial(
Train:   4%|▍         | 4/100 [00:09<03:59,  2.50s/ep, kl=35104.4817, reward=-2700.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 27/2903 (mode=train)
[run_serial] end mode=train steps=27 total_reward=-2700.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 5 / 100                                                                       │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             11724                                                                                  │
│  agent steps        11724                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       123872.282986                                                                          │
│  q loss (ep mean)   1030.235379                                                                            │
│  pi loss (ep mean)  -0.823208                                                                              │
│  eta (ep mean)      3.149443                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 5:   1%|          | 19/2903 [00:01<04:55,  9.75step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:   5%|▌         | 5/100 [00:11<03:39,  2.31s/ep, kl=130393.4013, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 6 / 100                                                                       │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             11743                                                                                  │
│  agent steps        11743                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       256366.025174                                                                          │
│  q loss (ep mean)   953.343129                                                                             │
│  pi loss (ep mean)  -0.869648                                                                              │
│  eta (ep mean)      3.284383                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 6:   1%|          | 19/2903 [00:01<05:03,  9.51step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:   6%|▌         | 6/100 [00:13<03:28,  2.22s/ep, kl=258787.8002, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 7 / 100                                                                       │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             11762                                                                                  │
│  agent steps        11762                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       287502.887153                                                                          │
│  q loss (ep mean)   936.092421                                                                             │
│  pi loss (ep mean)  -0.869696                                                                              │
│  eta (ep mean)      3.420503                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 7:   1%|          | 19/2903 [00:02<05:14,  9.16step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:   7%|▋         | 7/100 [00:15<03:23,  2.19s/ep, kl=287348.3125, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 8 / 100                                                                       │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             11781                                                                                  │
│  agent steps        11781                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       286362.764757                                                                          │
│  q loss (ep mean)   786.903985                                                                             │
│  pi loss (ep mean)  -0.869864                                                                              │
│  eta (ep mean)      3.546093                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 8:   1%|          | 19/2903 [00:02<05:25,  8.86step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:   8%|▊         | 8/100 [00:18<03:21,  2.19s/ep, kl=286391.5732, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 9 / 100                                                                       │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             11800                                                                                  │
│  agent steps        11800                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       287123.592014                                                                          │
│  q loss (ep mean)   796.006982                                                                             │
│  pi loss (ep mean)  -0.869763                                                                              │
│  eta (ep mean)      3.662615                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 9:   1%|          | 19/2903 [00:01<04:54,  9.81step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:   9%|▉         | 9/100 [00:20<03:13,  2.12s/ep, kl=288582.6645, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 10 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             11819                                                                                  │
│  agent steps        11819                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       288591.764757                                                                          │
│  q loss (ep mean)   716.493832                                                                             │
│  pi loss (ep mean)  -0.869915                                                                              │
│  eta (ep mean)      3.775674                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 10:   1%|          | 19/2903 [00:01<04:56,  9.72step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  10%|█         | 10/100 [00:22<03:07,  2.08s/ep, kl=288207.4910, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 11 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             11838                                                                                  │
│  agent steps        11838                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       293985.995660                                                                          │
│  q loss (ep mean)   659.357586                                                                             │
│  pi loss (ep mean)  -0.869756                                                                              │
│  eta (ep mean)      3.885802                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 11:   1%|          | 19/2903 [00:01<05:03,  9.52step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  11%|█         | 11/100 [00:24<03:04,  2.07s/ep, kl=293837.5584, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 12 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             11857                                                                                  │
│  agent steps        11857                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       295119.815104                                                                          │
│  q loss (ep mean)   653.527742                                                                             │
│  pi loss (ep mean)  -0.869789                                                                              │
│  eta (ep mean)      3.996513                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 12:   1%|          | 19/2903 [00:01<04:59,  9.62step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  12%|█▏        | 12/100 [00:26<03:00,  2.05s/ep, kl=293779.6834, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 13 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             11876                                                                                  │
│  agent steps        11876                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       298658.105903                                                                          │
│  q loss (ep mean)   689.396132                                                                             │
│  pi loss (ep mean)  -0.869710                                                                              │
│  eta (ep mean)      4.108182                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 13:   1%|          | 19/2903 [00:01<04:56,  9.74step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  13%|█▎        | 13/100 [00:28<02:56,  2.03s/ep, kl=298212.2582, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 14 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             11895                                                                                  │
│  agent steps        11895                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       294183.412326                                                                          │
│  q loss (ep mean)   628.107093                                                                             │
│  pi loss (ep mean)  -0.869727                                                                              │
│  eta (ep mean)      4.220989                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 14:   1%|          | 19/2903 [00:01<04:56,  9.73step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  14%|█▍        | 14/100 [00:30<02:53,  2.02s/ep, kl=293895.7311, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 15 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             11914                                                                                  │
│  agent steps        11914                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       305136.946181                                                                          │
│  q loss (ep mean)   675.331311                                                                             │
│  pi loss (ep mean)  -0.869829                                                                              │
│  eta (ep mean)      4.335464                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 15:   1%|          | 19/2903 [00:02<05:21,  8.98step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  15%|█▌        | 15/100 [00:32<02:55,  2.06s/ep, kl=304799.7615, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 16 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             11933                                                                                  │
│  agent steps        11933                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       296150.333333                                                                          │
│  q loss (ep mean)   664.483617                                                                             │
│  pi loss (ep mean)  -0.869817                                                                              │
│  eta (ep mean)      4.452575                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 16:   1%|          | 19/2903 [00:02<05:19,  9.03step/s, reward=-100.000, total=-1900.0]
[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  16%|█▌        | 16/100 [00:34<02:55,  2.09s/ep, kl=294977.7401, reward=-1900.0]

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 17 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             11952                                                                                  │
│  agent steps        11952                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       299270.771701                                                                          │
│  q loss (ep mean)   595.206980                                                                             │
│  pi loss (ep mean)  -0.869832                                                                              │
│  eta (ep mean)      4.570947                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 17:   1%|          | 19/2903 [00:02<05:14,  9.18step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  17%|█▋        | 17/100 [00:36<02:53,  2.10s/ep, kl=298302.9613, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 18 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             11971                                                                                  │
│  agent steps        11971                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       298224.453993                                                                          │
│  q loss (ep mean)   698.926680                                                                             │
│  pi loss (ep mean)  -0.869767                                                                              │
│  eta (ep mean)      4.692111                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 18:   1%|          | 19/2903 [00:02<05:03,  9.49step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  18%|█▊        | 18/100 [00:38<02:50,  2.08s/ep, kl=297027.4959, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 19 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             11990                                                                                  │
│  agent steps        11990                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       291805.227431                                                                          │
│  q loss (ep mean)   814.162116                                                                             │
│  pi loss (ep mean)  -0.869748                                                                              │
│  eta (ep mean)      4.814502                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 19:   1%|          | 19/2903 [00:02<05:11,  9.25step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  19%|█▉        | 19/100 [00:40<02:48,  2.09s/ep, kl=289638.7977, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 20 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12009                                                                                  │
│  agent steps        12009                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       289268.815972                                                                          │
│  q loss (ep mean)   778.287174                                                                             │
│  pi loss (ep mean)  -0.869784                                                                              │
│  eta (ep mean)      4.938096                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 20:   1%|          | 19/2903 [00:02<05:25,  8.87step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  20%|██        | 20/100 [00:42<02:49,  2.12s/ep, kl=290714.0444, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 21 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12028                                                                                  │
│  agent steps        12028                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       295096.312500                                                                          │
│  q loss (ep mean)   850.335700                                                                             │
│  pi loss (ep mean)  -0.869883                                                                              │
│  eta (ep mean)      5.064501                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 21:   1%|          | 19/2903 [00:02<05:19,  9.04step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  21%|██        | 21/100 [00:45<02:48,  2.13s/ep, kl=293310.6217, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 22 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12047                                                                                  │
│  agent steps        12047                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       305449.574653                                                                          │
│  q loss (ep mean)   868.014279                                                                             │
│  pi loss (ep mean)  -0.869845                                                                              │
│  eta (ep mean)      5.196441                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 22:   1%|          | 19/2903 [00:02<05:12,  9.22step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  22%|██▏       | 22/100 [00:47<02:45,  2.12s/ep, kl=303211.2484, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 23 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12066                                                                                  │
│  agent steps        12066                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       295329.099826                                                                          │
│  q loss (ep mean)   837.001453                                                                             │
│  pi loss (ep mean)  -0.869891                                                                              │
│  eta (ep mean)      5.334053                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 23:   1%|          | 19/2903 [00:02<05:17,  9.07step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  23%|██▎       | 23/100 [00:49<02:44,  2.13s/ep, kl=296007.8791, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 24 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12085                                                                                  │
│  agent steps        12085                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       297650.800347                                                                          │
│  q loss (ep mean)   906.233971                                                                             │
│  pi loss (ep mean)  -0.869804                                                                              │
│  eta (ep mean)      5.474049                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 24:   1%|          | 19/2903 [00:02<05:14,  9.18step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  24%|██▍       | 24/100 [00:51<02:41,  2.13s/ep, kl=298228.0888, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 25 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12104                                                                                  │
│  agent steps        12104                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       302733.876736                                                                          │
│  q loss (ep mean)   998.826274                                                                             │
│  pi loss (ep mean)  -0.869845                                                                              │
│  eta (ep mean)      5.619705                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 25:   1%|          | 19/2903 [00:02<05:11,  9.26step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  25%|██▌       | 25/100 [00:53<02:38,  2.12s/ep, kl=302000.8224, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 26 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12123                                                                                  │
│  agent steps        12123                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       305171.001736                                                                          │
│  q loss (ep mean)   909.905162                                                                             │
│  pi loss (ep mean)  -0.869840                                                                              │
│  eta (ep mean)      5.771057                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 26:   1%|          | 19/2903 [00:01<05:01,  9.56step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  26%|██▌       | 26/100 [00:55<02:34,  2.09s/ep, kl=304427.2319, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 27 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12142                                                                                  │
│  agent steps        12142                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       305305.878472                                                                          │
│  q loss (ep mean)   1114.876383                                                                            │
│  pi loss (ep mean)  -0.869803                                                                              │
│  eta (ep mean)      5.926436                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 27:   1%|          | 19/2903 [00:02<05:18,  9.05step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  27%|██▋       | 27/100 [00:57<02:34,  2.11s/ep, kl=303694.9638, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 28 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12161                                                                                  │
│  agent steps        12161                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       304507.213542                                                                          │
│  q loss (ep mean)   1097.926371                                                                            │
│  pi loss (ep mean)  -0.869884                                                                              │
│  eta (ep mean)      6.086278                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 28:   1%|          | 19/2903 [00:02<05:18,  9.07step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  28%|██▊       | 28/100 [00:59<02:32,  2.12s/ep, kl=307196.5609, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 29 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12180                                                                                  │
│  agent steps        12180                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       306620.204861                                                                          │
│  q loss (ep mean)   1136.861291                                                                            │
│  pi loss (ep mean)  -0.869750                                                                              │
│  eta (ep mean)      6.252615                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 29:   1%|          | 19/2903 [00:01<05:03,  9.51step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  29%|██▉       | 29/100 [01:01<02:28,  2.10s/ep, kl=306358.8586, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 30 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12199                                                                                  │
│  agent steps        12199                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       311776.406250                                                                          │
│  q loss (ep mean)   1270.042297                                                                            │
│  pi loss (ep mean)  -0.869862                                                                              │
│  eta (ep mean)      6.425570                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 30:   1%|          | 19/2903 [00:01<05:00,  9.61step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  30%|███       | 30/100 [01:03<02:25,  2.07s/ep, kl=311408.2204, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 31 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12218                                                                                  │
│  agent steps        12218                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       307243.914931                                                                          │
│  q loss (ep mean)   1361.764008                                                                            │
│  pi loss (ep mean)  -0.869831                                                                              │
│  eta (ep mean)      6.604394                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 31:   1%|          | 19/2903 [00:01<05:00,  9.60step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  31%|███       | 31/100 [01:05<02:21,  2.06s/ep, kl=306748.7039, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 32 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12237                                                                                  │
│  agent steps        12237                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       304662.765625                                                                          │
│  q loss (ep mean)   1387.060025                                                                            │
│  pi loss (ep mean)  -0.869847                                                                              │
│  eta (ep mean)      6.787551                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 32:   1%|          | 19/2903 [00:02<05:26,  8.83step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  32%|███▏      | 32/100 [01:08<02:22,  2.10s/ep, kl=305269.4474, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 33 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12256                                                                                  │
│  agent steps        12256                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       308390.147569                                                                          │
│  q loss (ep mean)   1265.914937                                                                            │
│  pi loss (ep mean)  -0.869819                                                                              │
│  eta (ep mean)      6.974400                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 33:   1%|          | 19/2903 [00:02<05:20,  8.99step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  33%|███▎      | 33/100 [01:10<02:21,  2.12s/ep, kl=307491.2352, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 34 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12275                                                                                  │
│  agent steps        12275                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       307099.901042                                                                          │
│  q loss (ep mean)   1366.678114                                                                            │
│  pi loss (ep mean)  -0.869719                                                                              │
│  eta (ep mean)      7.169044                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 34:   1%|          | 19/2903 [00:01<04:58,  9.65step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  34%|███▍      | 34/100 [01:12<02:17,  2.08s/ep, kl=306207.9095, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 35 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12294                                                                                  │
│  agent steps        12294                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       308684.829861                                                                          │
│  q loss (ep mean)   1538.093011                                                                            │
│  pi loss (ep mean)  -0.869846                                                                              │
│  eta (ep mean)      7.369611                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 35:   1%|          | 19/2903 [00:01<05:00,  9.60step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  35%|███▌      | 35/100 [01:14<02:14,  2.07s/ep, kl=309559.9441, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 36 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12313                                                                                  │
│  agent steps        12313                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       308175.515625                                                                          │
│  q loss (ep mean)   1951.354669                                                                            │
│  pi loss (ep mean)  -0.869781                                                                              │
│  eta (ep mean)      7.577976                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 36:   1%|          | 19/2903 [00:01<05:00,  9.59step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  36%|███▌      | 36/100 [01:16<02:11,  2.05s/ep, kl=307878.4326, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 37 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12332                                                                                  │
│  agent steps        12332                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       312125.930556                                                                          │
│  q loss (ep mean)   1779.438090                                                                            │
│  pi loss (ep mean)  -0.869716                                                                              │
│  eta (ep mean)      7.793282                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 37:   1%|          | 19/2903 [00:01<04:56,  9.72step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  37%|███▋      | 37/100 [01:18<02:08,  2.04s/ep, kl=312401.3618, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 38 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12351                                                                                  │
│  agent steps        12351                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       311798.015625                                                                          │
│  q loss (ep mean)   1832.987393                                                                            │
│  pi loss (ep mean)  -0.869874                                                                              │
│  eta (ep mean)      8.017993                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 38:   1%|          | 19/2903 [00:01<04:56,  9.72step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  38%|███▊      | 38/100 [01:20<02:05,  2.02s/ep, kl=312044.5773, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 39 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12370                                                                                  │
│  agent steps        12370                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       310650.314236                                                                          │
│  q loss (ep mean)   1813.373684                                                                            │
│  pi loss (ep mean)  -0.869742                                                                              │
│  eta (ep mean)      8.248523                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 39:   1%|          | 19/2903 [00:01<04:52,  9.85step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  39%|███▉      | 39/100 [01:22<02:02,  2.01s/ep, kl=312010.1266, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 40 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12389                                                                                  │
│  agent steps        12389                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       316021.769097                                                                          │
│  q loss (ep mean)   2023.755887                                                                            │
│  pi loss (ep mean)  -0.869804                                                                              │
│  eta (ep mean)      8.488966                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 40:   1%|          | 19/2903 [00:02<05:25,  8.85step/s, reward=-100.000, total=-1900.0]
[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  40%|████      | 40/100 [01:24<02:03,  2.06s/ep, kl=316443.5312, reward=-1900.0]

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 41 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12408                                                                                  │
│  agent steps        12408                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       311846.463542                                                                          │
│  q loss (ep mean)   2134.697191                                                                            │
│  pi loss (ep mean)  -0.869750                                                                              │
│  eta (ep mean)      8.738944                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 41:   1%|          | 19/2903 [00:02<05:20,  9.00step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  41%|████      | 41/100 [01:26<02:03,  2.09s/ep, kl=312387.2961, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 42 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12427                                                                                  │
│  agent steps        12427                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       297989.729167                                                                          │
│  q loss (ep mean)   2298.950033                                                                            │
│  pi loss (ep mean)  -0.869867                                                                              │
│  eta (ep mean)      8.993685                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 42:   1%|          | 19/2903 [00:02<05:07,  9.37step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  42%|████▏     | 42/100 [01:28<02:00,  2.08s/ep, kl=300271.7122, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 43 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12446                                                                                  │
│  agent steps        12446                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       310827.079861                                                                          │
│  q loss (ep mean)   2222.175232                                                                            │
│  pi loss (ep mean)  -0.869885                                                                              │
│  eta (ep mean)      9.253806                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 43:   1%|          | 19/2903 [00:01<04:54,  9.79step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  43%|████▎     | 43/100 [01:30<01:57,  2.05s/ep, kl=309764.7796, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 44 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12465                                                                                  │
│  agent steps        12465                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       329270.404514                                                                          │
│  q loss (ep mean)   2216.670837                                                                            │
│  pi loss (ep mean)  -0.869817                                                                              │
│  eta (ep mean)      9.528865                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 44:   1%|          | 19/2903 [00:01<04:58,  9.65step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  44%|████▍     | 44/100 [01:32<01:54,  2.04s/ep, kl=328130.5428, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 45 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12484                                                                                  │
│  agent steps        12484                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       320782.892361                                                                          │
│  q loss (ep mean)   2589.379876                                                                            │
│  pi loss (ep mean)  -0.869785                                                                              │
│  eta (ep mean)      9.821193                                                                               │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 45:   1%|          | 19/2903 [00:01<04:56,  9.71step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  45%|████▌     | 45/100 [01:34<01:51,  2.03s/ep, kl=321125.2007, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 46 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12503                                                                                  │
│  agent steps        12503                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       324145.963542                                                                          │
│  q loss (ep mean)   2281.105896                                                                            │
│  pi loss (ep mean)  -0.869796                                                                              │
│  eta (ep mean)      10.123007                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 46:   1%|          | 19/2903 [00:01<05:03,  9.52step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  46%|████▌     | 46/100 [01:36<01:49,  2.03s/ep, kl=325511.9474, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 47 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12522                                                                                  │
│  agent steps        12522                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       314964.241319                                                                          │
│  q loss (ep mean)   2505.179518                                                                            │
│  pi loss (ep mean)  -0.869806                                                                              │
│  eta (ep mean)      10.436621                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 47:   1%|          | 19/2903 [00:01<04:55,  9.75step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  47%|████▋     | 47/100 [01:38<01:46,  2.02s/ep, kl=316416.9391, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 48 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12541                                                                                  │
│  agent steps        12541                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       319312.670139                                                                          │
│  q loss (ep mean)   2425.796292                                                                            │
│  pi loss (ep mean)  -0.869749                                                                              │
│  eta (ep mean)      10.755496                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 48:   1%|          | 19/2903 [00:02<05:09,  9.30step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  48%|████▊     | 48/100 [01:40<01:45,  2.04s/ep, kl=321312.3372, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 49 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12560                                                                                  │
│  agent steps        12560                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       305285.220486                                                                          │
│  q loss (ep mean)   2835.743557                                                                            │
│  pi loss (ep mean)  -0.869738                                                                              │
│  eta (ep mean)      11.086000                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 49:   1%|          | 19/2903 [00:02<05:21,  8.97step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  49%|████▉     | 49/100 [01:42<01:45,  2.08s/ep, kl=307764.6102, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 50 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12579                                                                                  │
│  agent steps        12579                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       310405.180556                                                                          │
│  q loss (ep mean)   2925.985948                                                                            │
│  pi loss (ep mean)  -0.869885                                                                              │
│  eta (ep mean)      11.422809                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 50:   1%|          | 19/2903 [00:02<05:12,  9.22step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  50%|█████     | 50/100 [01:45<01:44,  2.08s/ep, kl=312058.9737, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 51 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12598                                                                                  │
│  agent steps        12598                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       327494.802083                                                                          │
│  q loss (ep mean)   3114.758057                                                                            │
│  pi loss (ep mean)  -0.869782                                                                              │
│  eta (ep mean)      11.773749                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 51:   1%|          | 19/2903 [00:01<04:58,  9.65step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  51%|█████     | 51/100 [01:47<01:41,  2.06s/ep, kl=325123.3865, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 52 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12617                                                                                  │
│  agent steps        12617                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       320773.987847                                                                          │
│  q loss (ep mean)   3081.999125                                                                            │
│  pi loss (ep mean)  -0.869725                                                                              │
│  eta (ep mean)      12.148407                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 52:   1%|          | 19/2903 [00:01<05:00,  9.61step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  52%|█████▏    | 52/100 [01:49<01:38,  2.05s/ep, kl=322223.9523, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 53 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12636                                                                                  │
│  agent steps        12636                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       323544.736111                                                                          │
│  q loss (ep mean)   3323.308160                                                                            │
│  pi loss (ep mean)  -0.869813                                                                              │
│  eta (ep mean)      12.535330                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 53:   1%|          | 19/2903 [00:02<05:10,  9.28step/s, reward=-100.000, total=-1900.0]
[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  53%|█████▎    | 53/100 [01:51<01:36,  2.06s/ep, kl=323614.5773, reward=-1900.0]

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 54 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12655                                                                                  │
│  agent steps        12655                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       322698.720486                                                                          │
│  q loss (ep mean)   3392.836392                                                                            │
│  pi loss (ep mean)  -0.869764                                                                              │
│  eta (ep mean)      12.936424                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 54:   1%|          | 19/2903 [00:01<05:03,  9.52step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  54%|█████▍    | 54/100 [01:53<01:34,  2.05s/ep, kl=321931.7747, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 55 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12674                                                                                  │
│  agent steps        12674                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       330885.151042                                                                          │
│  q loss (ep mean)   3511.436686                                                                            │
│  pi loss (ep mean)  -0.869802                                                                              │
│  eta (ep mean)      13.351759                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 55:   1%|          | 19/2903 [00:01<05:00,  9.60step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  55%|█████▌    | 55/100 [01:55<01:31,  2.04s/ep, kl=331793.2122, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 56 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12693                                                                                  │
│  agent steps        12693                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       311870.449653                                                                          │
│  q loss (ep mean)   3574.600410                                                                            │
│  pi loss (ep mean)  -0.869757                                                                              │
│  eta (ep mean)      13.782308                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 56:   1%|          | 19/2903 [00:02<05:04,  9.48step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  56%|█████▌    | 56/100 [01:57<01:30,  2.05s/ep, kl=312724.1891, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 57 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12712                                                                                  │
│  agent steps        12712                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       319272.677083                                                                          │
│  q loss (ep mean)   3179.125359                                                                            │
│  pi loss (ep mean)  -0.869750                                                                              │
│  eta (ep mean)      14.220713                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 57:   1%|          | 19/2903 [00:02<05:29,  8.75step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  57%|█████▋    | 57/100 [01:59<01:30,  2.10s/ep, kl=321553.3355, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 58 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12731                                                                                  │
│  agent steps        12731                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       325591.607639                                                                          │
│  q loss (ep mean)   3320.093085                                                                            │
│  pi loss (ep mean)  -0.869814                                                                              │
│  eta (ep mean)      14.683877                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 58:   1%|          | 19/2903 [00:02<05:27,  8.82step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  58%|█████▊    | 58/100 [02:01<01:29,  2.13s/ep, kl=324455.3635, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 59 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12750                                                                                  │
│  agent steps        12750                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       335247.958333                                                                          │
│  q loss (ep mean)   3652.149902                                                                            │
│  pi loss (ep mean)  -0.869901                                                                              │
│  eta (ep mean)      15.167025                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 59:   1%|          | 19/2903 [00:01<05:02,  9.53step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  59%|█████▉    | 59/100 [02:03<01:26,  2.10s/ep, kl=336381.6711, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 60 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12769                                                                                  │
│  agent steps        12769                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       326240.076389                                                                          │
│  q loss (ep mean)   3536.304077                                                                            │
│  pi loss (ep mean)  -0.869746                                                                              │
│  eta (ep mean)      15.677219                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 60:   1%|          | 19/2903 [00:01<05:00,  9.61step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  60%|██████    | 60/100 [02:05<01:22,  2.07s/ep, kl=325951.6891, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 61 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12788                                                                                  │
│  agent steps        12788                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       336343.381944                                                                          │
│  q loss (ep mean)   4079.766398                                                                            │
│  pi loss (ep mean)  -0.869826                                                                              │
│  eta (ep mean)      16.202760                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 61:   1%|          | 19/2903 [00:02<05:04,  9.47step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  61%|██████    | 61/100 [02:07<01:20,  2.07s/ep, kl=335410.3520, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 62 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12807                                                                                  │
│  agent steps        12807                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       326909.215278                                                                          │
│  q loss (ep mean)   3908.014784                                                                            │
│  pi loss (ep mean)  -0.869767                                                                              │
│  eta (ep mean)      16.753462                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 62:   1%|          | 19/2903 [00:01<05:01,  9.55step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  62%|██████▏   | 62/100 [02:09<01:18,  2.06s/ep, kl=326832.7993, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 63 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12826                                                                                  │
│  agent steps        12826                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       337917.065972                                                                          │
│  q loss (ep mean)   4962.117581                                                                            │
│  pi loss (ep mean)  -0.869807                                                                              │
│  eta (ep mean)      17.320415                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 63:   1%|          | 19/2903 [00:01<04:56,  9.73step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  63%|██████▎   | 63/100 [02:11<01:15,  2.04s/ep, kl=337627.6612, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 64 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12845                                                                                  │
│  agent steps        12845                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       327369.444444                                                                          │
│  q loss (ep mean)   3936.567871                                                                            │
│  pi loss (ep mean)  -0.869825                                                                              │
│  eta (ep mean)      17.914263                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 64:   1%|          | 19/2903 [00:01<05:00,  9.61step/s, reward=-100.000, total=-1900.0]
[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  64%|██████▍   | 64/100 [02:13<01:13,  2.03s/ep, kl=327039.2401, reward=-1900.0]

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 65 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12864                                                                                  │
│  agent steps        12864                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       332443.861111                                                                          │
│  q loss (ep mean)   4812.343370                                                                            │
│  pi loss (ep mean)  -0.869755                                                                              │
│  eta (ep mean)      18.523694                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 65:   1%|          | 19/2903 [00:02<05:14,  9.16step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  65%|██████▌   | 65/100 [02:15<01:12,  2.06s/ep, kl=331446.7500, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 66 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12883                                                                                  │
│  agent steps        12883                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       329235.506944                                                                          │
│  q loss (ep mean)   4816.847371                                                                            │
│  pi loss (ep mean)  -0.869776                                                                              │
│  eta (ep mean)      19.156314                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 66:   1%|          | 19/2903 [00:02<05:31,  8.71step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  66%|██████▌   | 66/100 [02:18<01:11,  2.11s/ep, kl=330768.0987, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 67 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12902                                                                                  │
│  agent steps        12902                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       316480.576389                                                                          │
│  q loss (ep mean)   4436.870212                                                                            │
│  pi loss (ep mean)  -0.869829                                                                              │
│  eta (ep mean)      19.806481                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 67:   1%|          | 19/2903 [00:02<05:18,  9.05step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  67%|██████▋   | 67/100 [02:20<01:09,  2.12s/ep, kl=315642.1151, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 68 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12921                                                                                  │
│  agent steps        12921                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       330492.225694                                                                          │
│  q loss (ep mean)   4771.787720                                                                            │
│  pi loss (ep mean)  -0.869845                                                                              │
│  eta (ep mean)      20.470579                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 68:   1%|          | 19/2903 [00:01<05:00,  9.58step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  68%|██████▊   | 68/100 [02:22<01:06,  2.09s/ep, kl=329773.6875, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 69 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12940                                                                                  │
│  agent steps        12940                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       329803.741319                                                                          │
│  q loss (ep mean)   4792.734266                                                                            │
│  pi loss (ep mean)  -0.869847                                                                              │
│  eta (ep mean)      21.172733                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 69:   1%|          | 19/2903 [00:02<05:05,  9.45step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  69%|██████▉   | 69/100 [02:24<01:04,  2.08s/ep, kl=329243.3273, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 70 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12959                                                                                  │
│  agent steps        12959                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       343356.550347                                                                          │
│  q loss (ep mean)   5319.852702                                                                            │
│  pi loss (ep mean)  -0.869903                                                                              │
│  eta (ep mean)      21.915393                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 70:   1%|          | 19/2903 [00:02<05:08,  9.35step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  70%|███████   | 70/100 [02:26<01:02,  2.08s/ep, kl=343725.5280, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 71 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12978                                                                                  │
│  agent steps        12978                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       332252.053819                                                                          │
│  q loss (ep mean)   5861.739461                                                                            │
│  pi loss (ep mean)  -0.869817                                                                              │
│  eta (ep mean)      22.695409                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 71:   1%|          | 19/2903 [00:01<05:02,  9.54step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  71%|███████   | 71/100 [02:28<00:59,  2.07s/ep, kl=333048.5444, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 72 / 100                                                                      │
│  step               19 / 2903 (0.7%)                                                                       │
│  sim time           7.6 s                                                                                  │
│  step reward        -100.0000                                                                              │
│  episode return     -1900.00                                                                               │
│  body z angle       -2.0745 rad                                                                            │
│  omega sat          0.0244 rad/s                                                                           │
│  image smear        0.350 px                                                                               │
│  image quality      0.3501                                                                                 │
│  buffer             12997                                                                                  │
│  agent steps        12997                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       334961.319444                                                                          │
│  q loss (ep mean)   5678.353651                                                                            │
│  pi loss (ep mean)  -0.869842                                                                              │
│  eta (ep mean)      23.498348                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 72:   1%|          | 19/2903 [00:02<05:05,  9.45step/s, reward=-100.000, total=-1900.0]

d:\code\sem-proj-asc\backend\notebooks\s01\s01_utils\training_workflow.py:767: UserWarning: [run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
  return setup.runner.run_serial(
Train:  72%|███████▏  | 72/100 [02:30<00:57,  2.06s/ep, kl=334594.0526, reward=-1900.0]

[run_serial] WARNING: episode ended early — capture budget exhausted at step 19/2903 (mode=train)
[run_serial] end mode=train steps=19 total_reward=-1900.000000 avg_reward=-100.000000
train ep 73:   1%|          | 15/2903 [00:01<05:05,  9.46step/s]

Train:  72%|███████▏  | 72/100 [02:32<00:59,  2.11s/ep, kl=334594.0526, reward=-1900.0]

KeyboardInterrupt:

In [ ]:
tw.print_training_kpis(result)

In [ ]:
from utils.notebook.video import init_video_cell, play_saved_video

init_video_cell()

from utils.notebook.video import init_video_cell, play_saved_video

init_video_cell()
tw.display_training_artifacts(result)
video_path = result.artifact_paths["eval_best_video"]
if video_path.exists():
    play_saved_video(video_path)