In [1]:
"""
S01 MPO training — integrate notebooks 01–07 mission context.

Scenario:
  - Same mission profile as notebook 07 baseline overflight (50-target meridian grid,
    seeded clouds over the corridor, dual camera, attitude safety on, image quality)
  - Controller features selected via ControllerFeatureConfig (see cell below)
  - 10× baseline overflight warmup (notebook 07 policy, 2-D buffer) → train → eval
  - Preflight: inline feature checks + full ML training pytest suite

Verification: s01_utils/training_workflow.py
Artifacts: autonomous_control/models/nb-s01-08-<timestamp>/
Export: eval_best.mp4 in run directory
"""

'\nS01 MPO training — integrate notebooks 01–07 mission context.\n\nScenario:\n  - Same mission profile as notebook 07 baseline overflight (50-target meridian grid,\n    seeded clouds over the corridor, dual camera, attitude safety on, image quality)\n  - Controller features selected via ControllerFeatureConfig (see cell below)\n  - 10× baseline overflight warmup (notebook 07 policy, 2-D buffer) → train → eval\n  - Preflight: inline feature checks + full ML training pytest suite\n\nVerification: s01_utils/training_workflow.py\nArtifacts: autonomous_control/models/nb-s01-08-<timestamp>/\nExport: eval_best.mp4 in run directory\n'

In [2]:
def setup_notebook_paths():
    """
    Configure Python paths and working directory for running the S01 training notebook.

    - Walks up directories from the current working directory until it finds the 'simulation' folder,
      which marks the backend root.
    - Changes the working directory to the backend root to ensure relative paths are correct.
    - Adds both the backend root and the S01 notebook utilities directory to sys.path for imports.

    This setup is required for importing backend modules and utility code in other cells.
    """
    import os
    import sys
    from pathlib import Path

    notebook_dir = Path.cwd()
    backend_root = notebook_dir
    for _ in range(6):
        if (backend_root / "simulation").is_dir():
            break
        backend_root = backend_root.parent
    os.chdir(backend_root)
    sys.path.insert(0, str(backend_root))
    _s01_dir = backend_root / "notebooks" / "s01"
    sys.path.insert(0, str(_s01_dir))
    print(f"backend_root={backend_root}")

setup_notebook_paths()

backend_root=c:\Users\cedri\code\autonomous-satellite-control-eth-sem-proj\backend

In [3]:
import importlib

import s01_utils.training_workflow as tw

importlib.reload(tw)

# Fast gate: inline checks + unit pytest (~3s). Re-runs are skipped via session/disk cache.
# For full serial episode-runner tests (~80s): tw.run_s01_training_preflight_gate(integration_pytest=True, force=True)
tw.run_s01_training_preflight_gate()

c:\Users\cedri\miniconda3\envs\auto-sat\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Using device: cpu
Using device: cpu
Using device: cpu

True

In [4]:
from dataclasses import replace

# Single source of truth: s01_utils/training_workflow.py (timestep keys + mission scalars).
# Customize with replace(), e.g. replace(tw.S01_TRAINING_FEATURE_CONFIG, include_capture_budget=False)
FEATURE_CONFIG = tw.S01_TRAINING_FEATURE_CONFIG

WORKFLOW_CONFIG = tw.TrainingWorkflowConfig(
    seed=7,
    train_episodes=5,
    feature_config=FEATURE_CONFIG,
)

# Mission profile for layout tables (same as training).
_mission_resolved = tw.build_s01_training_mission_setup(seed=WORKFLOW_CONFIG.seed).resolve(
    require_camera=True
)
_secondary_bins = int(_mission_resolved.secondary_camera_observation_line_n_bins)
_n_targets = len(_mission_resolved.target_areas or ())
tw.display_feature_tables(
    FEATURE_CONFIG,
    secondary_camera_bins=_secondary_bins,
    n_mission_targets=_n_targets,
)

### Controller feature selection (`ControllerFeatureConfig`)

Edit `S01_TRAINING_FEATURE_CONFIG` in `s01_utils/training_workflow.py` (timestep key tuples **and** `include_capture_budget` / `include_target_bearing_errors`). Notebook 08 should assign `FEATURE_CONFIG = tw.S01_TRAINING_FEATURE_CONFIG` rather than duplicating keys.

### Controller encoder routing (scalar **54**, vision streams **2**)

### Observation code legend (vision line bins)

In [5]:
setup = tw.build_training_workflow_setup(WORKFLOW_CONFIG)
tw.print_training_setup_summary(setup)
tw.display_feature_snapshot_tables(setup)

Using device: cpu
S01 MPO training setup (notebook 07 baseline overflight profile)
  run_dir:           C:\Users\cedri\code\autonomous-satellite-control-eth-sem-proj\backend\autonomous_control\models\nb-s01-08-2026-06-26_09-12-30
  seed:              7
  altitude:          528.8 km
  targets:           50
  clouds:            25 (seeded over target corridor)
  orbit window:      -32.7° .. 37.1°
  episode steps:     2904
  attitude safety:   on (training_episode_simulation_config)
  scalar dim:        54
  vision streams:    [('camera_observation_line_codes', 100), ('secondary_camera_observation_line_codes', 200)]
  encoder trunk:     180-D
  secondary bins:    200
  feature keys:      ['body_z_angle_rad', 'omega_sat_rad_s', 'theta_orbit_rad', 'camera_observation_line_codes', 'secondary_camera_observation_line_codes']
  warmup episodes:   10
  train episodes:    5
  eval episodes:     2
  MPO batch_size:    256
  MPO gamma:         0.99
  MPO LRs q/pi/eta:  0.00045/0.00015/0.001
  target_kl mu/sigma: 0.1/0.0001
  reward flags:      image_quality_capture, outer_gate
  early stop:        False (warmup/train; eval always full horizon)

c:\Users\cedri\code\autonomous-satellite-control-eth-sem-proj\backend\simulation\stepper.py:171: UserWarning: controller_update_interval (1 s) is not an integer multiple of simulation_timestep (0.4 s); using nearest multiple: 0.8 s (2 sim steps).
  self._controller_interval_steps, self._effective_controller_interval_s = resolve_controller_interval_steps(

### Scalar features at episode start (MLP branch)

### Vision line features at episode start (CNN branches)

Structured `ControllerObservation`: scalars **54**, vision **camera_observation_line_codes 100 bins, secondary_camera_observation_line_codes 200 bins** → encoder trunk **180**-D.

In [6]:
result = tw.run_training_workflow(setup, show_progress=True)

Warmup:   0%|          | 0/10 [00:00<?, ?ep/s]

╭──────────────────────────────────────────────── Simulation info ────────────────────────────────────────────────╮
│  Parameter                                     Value                                                            │
│  episode duration                              1160.93 s                                                        │
│  simulation timestep                           0.399906 s                                                       │
│  integration steps                             2903 (+1 state samples)                                          │
│  orbit altitude                                528.76 km                                                        │
│  orbit period                                  5703.8 s                                                         │
│  theta center offset                           90.00 deg                                                        │
│  episode theta start (rel. center)             -32.693 deg                                                      │
│  episode theta end (rel. center)               37.091 deg                                                       │
│  sat motion span scale                         1.050                                                            │
│  sat z offset                                  0.00 deg                                                         │
│  target areas                                  50                                                               │
│  target phi stripe                             79.93 deg .. 104.46 deg                                          │
│  cloud patches                                 25                                                               │
│  render mode                                   headless                                                         │
│  torque command source                         external                                                         │
│  torque policy                                 sequential_target_baseline                                       │
│  attitude controller                           enabled                                                          │
│  control stack (display)                       sequential_target_baseline · attitude_controller                 │
│  controller seed                               -                                                                │
│  controller update (configured)                1 s                                                              │
│  controller update (effective)                 0.8 s (2 steps)                                                  │
│  reaction-wheel torque max                     0.1000 N*m                                                       │
│  attitude safety cutoff                        |omega_sat| > 3.00 deg/s -> block opposing torque                │
│  camera kernel backend                         accelerated                                                      │
│  reward shaping                                outer_gate                                                       │
│  episode runner mode                           warmup                                                           │
│  agent                                         MPOAgent                                                         │
│  Camera 1 (primary) - role                     shapes reward (observation line + strip)                         │
│  Camera 1 (primary) - tilt off nadir           0.00 deg                                                         │
│  Camera 1 (primary) - FOV (cross x along)      1.61 deg x 1.20 deg                                              │
│  Camera 1 (primary) - resolution               9344 x 7000 px                                                   │
│  Camera 1 (primary) - pixel pitch              3.20 um                                                          │
│  Camera 1 (primary) - focal length             1067.0 mm                                                        │
│  Camera 1 (primary) - GSD @ 528.8 km           1.586 m                                                          │
│  Camera 1 (primary) - observation line bins    100                                                              │
│  Camera 1 (primary) - strip ray samples        96                                                               │
│  Camera 1 (primary) - sim vertical FOV         1.203 deg                                                        │
│  Camera 1 (primary) - exposure time            100 us (image smear)                                             │
│  Camera 2 (secondary) - role                   cloud/context only (no exposure in reward)                       │
│  Camera 2 (secondary) - tilt off nadir         25.00 deg                                                        │
│  Camera 2 (secondary) - FOV (cross x along)    102.45 deg x 70.00 deg                                           │
│  Camera 2 (secondary) - resolution             5312 x 2988 px                                                   │
│  Camera 2 (secondary) - pixel pitch            1.55 um                                                          │
│  Camera 2 (secondary) - focal length           3.3 mm                                                           │
│  Camera 2 (secondary) - GSD @ 528.8 km         247.818 m                                                        │
│  Camera 2 (secondary) - observation line bins  200                                                              │
│  Camera 2 (secondary) - sim vertical FOV       70.000 deg                                                       │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 1 / 10                                                                          │
│  step            400 / 2903 (13.8%)                                                                        │
│  sim time        160.0 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  0.00                                                                                      │
│  body z angle    -2.2659 rad                                                                               │
│  omega sat       -0.0399 rad/s                                                                             │
│  image smear     1.890 px                                                                                  │
│  image quality   0.0880                                                                                    │
│  buffer          399                                                                                       │
│  agent steps     399                                                                                       │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 1 / 10                                                                          │
│  step            800 / 2903 (27.6%)                                                                        │
│  sim time        319.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  0.00                                                                                      │
│  body z angle    -2.2578 rad                                                                               │
│  omega sat       -0.0277 rad/s                                                                             │
│  image smear     1.522 px                                                                                  │
│  image quality   0.1011                                                                                    │
│  buffer          799                                                                                       │
│  agent steps     799                                                                                       │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 1 / 10                                                                          │
│  step            1200 / 2903 (41.3%)                                                                       │
│  sim time        479.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.5615 rad                                                                               │
│  omega sat       0.0014 rad/s                                                                              │
│  image smear     0.431 px                                                                                  │
│  image quality   0.3043                                                                                    │
│  buffer          1199                                                                                      │
│  agent steps     1199                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 1 / 10                                                                          │
│  step            1600 / 2903 (55.1%)                                                                       │
│  sim time        639.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.4670 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2999                                                                                    │
│  buffer          1599                                                                                      │
│  agent steps     1599                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 1 / 10                                                                          │
│  step            2000 / 2903 (68.9%)                                                                       │
│  sim time        799.8 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.2908 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2999                                                                                    │
│  buffer          1999                                                                                      │
│  agent steps     1999                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 1 / 10                                                                          │
│  step            2400 / 2903 (82.7%)                                                                       │
│  sim time        959.8 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.1146 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2998                                                                                    │
│  buffer          2399                                                                                      │
│  agent steps     2399                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 1 / 10                                                                          │
│  step            2800 / 2903 (96.5%)                                                                       │
│  sim time        1119.7 s                                                                                  │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -0.9384 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2997                                                                                    │
│  buffer          2799                                                                                      │
│  agent steps     2799                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 1 / 10                                                                          │
│  step            2903 / 2903 (100.0%)                                                                      │
│  sim time        1160.9 s                                                                                  │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -0.8930 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2996                                                                                    │
│  buffer          2902                                                                                      │
│  agent steps     2902                                                                                      │
│  status          episode done                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

warmup ep 1: 100%|██████████| 2903/2903 [01:13<00:00, 39.47step/s, reward=0.000, total=140.6]

Warmup:  10%|█         | 1/10 [01:13<11:02, 73.58s/ep]

[run_serial] end mode=warmup steps=2903 total_reward=140.590923 avg_reward=0.048430

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 2 / 10                                                                          │
│  step            400 / 2903 (13.8%)                                                                        │
│  sim time        160.0 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  0.00                                                                                      │
│  body z angle    -2.2659 rad                                                                               │
│  omega sat       -0.0399 rad/s                                                                             │
│  image smear     1.890 px                                                                                  │
│  image quality   0.0880                                                                                    │
│  buffer          3302                                                                                      │
│  agent steps     3302                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 2 / 10                                                                          │
│  step            800 / 2903 (27.6%)                                                                        │
│  sim time        319.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  0.00                                                                                      │
│  body z angle    -2.2578 rad                                                                               │
│  omega sat       -0.0277 rad/s                                                                             │
│  image smear     1.522 px                                                                                  │
│  image quality   0.1011                                                                                    │
│  buffer          3702                                                                                      │
│  agent steps     3702                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 2 / 10                                                                          │
│  step            1200 / 2903 (41.3%)                                                                       │
│  sim time        479.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.5615 rad                                                                               │
│  omega sat       0.0014 rad/s                                                                              │
│  image smear     0.431 px                                                                                  │
│  image quality   0.3043                                                                                    │
│  buffer          4102                                                                                      │
│  agent steps     4102                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 2 / 10                                                                          │
│  step            1600 / 2903 (55.1%)                                                                       │
│  sim time        639.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.4670 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2999                                                                                    │
│  buffer          4502                                                                                      │
│  agent steps     4502                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 2 / 10                                                                          │
│  step            2000 / 2903 (68.9%)                                                                       │
│  sim time        799.8 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.2908 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2999                                                                                    │
│  buffer          4902                                                                                      │
│  agent steps     4902                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 2 / 10                                                                          │
│  step            2400 / 2903 (82.7%)                                                                       │
│  sim time        959.8 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.1146 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2998                                                                                    │
│  buffer          5302                                                                                      │
│  agent steps     5302                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 2 / 10                                                                          │
│  step            2800 / 2903 (96.5%)                                                                       │
│  sim time        1119.7 s                                                                                  │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -0.9384 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2997                                                                                    │
│  buffer          5702                                                                                      │
│  agent steps     5702                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 2 / 10                                                                          │
│  step            2903 / 2903 (100.0%)                                                                      │
│  sim time        1160.9 s                                                                                  │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -0.8930 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2996                                                                                    │
│  buffer          5805                                                                                      │
│  agent steps     5805                                                                                      │
│  status          episode done                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

warmup ep 2: 100%|██████████| 2903/2903 [01:13<00:00, 39.44step/s, reward=0.000, total=140.6]

Warmup:  20%|██        | 2/10 [02:27<09:48, 73.62s/ep]

[run_serial] end mode=warmup steps=2903 total_reward=140.590923 avg_reward=0.048430

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 3 / 10                                                                          │
│  step            400 / 2903 (13.8%)                                                                        │
│  sim time        160.0 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  0.00                                                                                      │
│  body z angle    -2.2659 rad                                                                               │
│  omega sat       -0.0399 rad/s                                                                             │
│  image smear     1.890 px                                                                                  │
│  image quality   0.0880                                                                                    │
│  buffer          6205                                                                                      │
│  agent steps     6205                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 3 / 10                                                                          │
│  step            800 / 2903 (27.6%)                                                                        │
│  sim time        319.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  0.00                                                                                      │
│  body z angle    -2.2578 rad                                                                               │
│  omega sat       -0.0277 rad/s                                                                             │
│  image smear     1.522 px                                                                                  │
│  image quality   0.1011                                                                                    │
│  buffer          6605                                                                                      │
│  agent steps     6605                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 3 / 10                                                                          │
│  step            1200 / 2903 (41.3%)                                                                       │
│  sim time        479.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.5615 rad                                                                               │
│  omega sat       0.0014 rad/s                                                                              │
│  image smear     0.431 px                                                                                  │
│  image quality   0.3043                                                                                    │
│  buffer          7005                                                                                      │
│  agent steps     7005                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 3 / 10                                                                          │
│  step            1600 / 2903 (55.1%)                                                                       │
│  sim time        639.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.4670 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2999                                                                                    │
│  buffer          7405                                                                                      │
│  agent steps     7405                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 3 / 10                                                                          │
│  step            2000 / 2903 (68.9%)                                                                       │
│  sim time        799.8 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.2908 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2999                                                                                    │
│  buffer          7805                                                                                      │
│  agent steps     7805                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 3 / 10                                                                          │
│  step            2400 / 2903 (82.7%)                                                                       │
│  sim time        959.8 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.1146 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2998                                                                                    │
│  buffer          8205                                                                                      │
│  agent steps     8205                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 3 / 10                                                                          │
│  step            2800 / 2903 (96.5%)                                                                       │
│  sim time        1119.7 s                                                                                  │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -0.9384 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2997                                                                                    │
│  buffer          8605                                                                                      │
│  agent steps     8605                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 3 / 10                                                                          │
│  step            2903 / 2903 (100.0%)                                                                      │
│  sim time        1160.9 s                                                                                  │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -0.8930 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2996                                                                                    │
│  buffer          8708                                                                                      │
│  agent steps     8708                                                                                      │
│  status          episode done                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

warmup ep 3: 100%|██████████| 2903/2903 [01:13<00:00, 39.37step/s, reward=0.000, total=140.6]

Warmup:  30%|███       | 3/10 [03:41<08:35, 73.70s/ep]

[run_serial] end mode=warmup steps=2903 total_reward=140.590923 avg_reward=0.048430

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 4 / 10                                                                          │
│  step            400 / 2903 (13.8%)                                                                        │
│  sim time        160.0 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  0.00                                                                                      │
│  body z angle    -2.2659 rad                                                                               │
│  omega sat       -0.0399 rad/s                                                                             │
│  image smear     1.890 px                                                                                  │
│  image quality   0.0880                                                                                    │
│  buffer          9108                                                                                      │
│  agent steps     9108                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 4 / 10                                                                          │
│  step            800 / 2903 (27.6%)                                                                        │
│  sim time        319.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  0.00                                                                                      │
│  body z angle    -2.2578 rad                                                                               │
│  omega sat       -0.0277 rad/s                                                                             │
│  image smear     1.522 px                                                                                  │
│  image quality   0.1011                                                                                    │
│  buffer          9508                                                                                      │
│  agent steps     9508                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 4 / 10                                                                          │
│  step            1200 / 2903 (41.3%)                                                                       │
│  sim time        479.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.5615 rad                                                                               │
│  omega sat       0.0014 rad/s                                                                              │
│  image smear     0.431 px                                                                                  │
│  image quality   0.3043                                                                                    │
│  buffer          9908                                                                                      │
│  agent steps     9908                                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 4 / 10                                                                          │
│  step            1600 / 2903 (55.1%)                                                                       │
│  sim time        639.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.4670 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2999                                                                                    │
│  buffer          10308                                                                                     │
│  agent steps     10308                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 4 / 10                                                                          │
│  step            2000 / 2903 (68.9%)                                                                       │
│  sim time        799.8 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.2908 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2999                                                                                    │
│  buffer          10708                                                                                     │
│  agent steps     10708                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 4 / 10                                                                          │
│  step            2400 / 2903 (82.7%)                                                                       │
│  sim time        959.8 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.1146 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2998                                                                                    │
│  buffer          11108                                                                                     │
│  agent steps     11108                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 4 / 10                                                                          │
│  step            2800 / 2903 (96.5%)                                                                       │
│  sim time        1119.7 s                                                                                  │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -0.9384 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2997                                                                                    │
│  buffer          11508                                                                                     │
│  agent steps     11508                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 4 / 10                                                                          │
│  step            2903 / 2903 (100.0%)                                                                      │
│  sim time        1160.9 s                                                                                  │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -0.8930 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2996                                                                                    │
│  buffer          11611                                                                                     │
│  agent steps     11611                                                                                     │
│  status          episode done                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

warmup ep 4: 100%|██████████| 2903/2903 [01:13<00:00, 39.27step/s, reward=0.000, total=140.6]

Warmup:  40%|████      | 4/10 [04:54<07:22, 73.80s/ep]

[run_serial] end mode=warmup steps=2903 total_reward=140.590923 avg_reward=0.048430

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 5 / 10                                                                          │
│  step            400 / 2903 (13.8%)                                                                        │
│  sim time        160.0 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  0.00                                                                                      │
│  body z angle    -2.2659 rad                                                                               │
│  omega sat       -0.0399 rad/s                                                                             │
│  image smear     1.890 px                                                                                  │
│  image quality   0.0880                                                                                    │
│  buffer          12011                                                                                     │
│  agent steps     12011                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 5 / 10                                                                          │
│  step            800 / 2903 (27.6%)                                                                        │
│  sim time        319.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  0.00                                                                                      │
│  body z angle    -2.2578 rad                                                                               │
│  omega sat       -0.0277 rad/s                                                                             │
│  image smear     1.522 px                                                                                  │
│  image quality   0.1011                                                                                    │
│  buffer          12411                                                                                     │
│  agent steps     12411                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 5 / 10                                                                          │
│  step            1200 / 2903 (41.3%)                                                                       │
│  sim time        479.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.5615 rad                                                                               │
│  omega sat       0.0014 rad/s                                                                              │
│  image smear     0.431 px                                                                                  │
│  image quality   0.3043                                                                                    │
│  buffer          12811                                                                                     │
│  agent steps     12811                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 5 / 10                                                                          │
│  step            1600 / 2903 (55.1%)                                                                       │
│  sim time        639.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.4670 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2999                                                                                    │
│  buffer          13211                                                                                     │
│  agent steps     13211                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 5 / 10                                                                          │
│  step            2000 / 2903 (68.9%)                                                                       │
│  sim time        799.8 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.2908 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2999                                                                                    │
│  buffer          13611                                                                                     │
│  agent steps     13611                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 5 / 10                                                                          │
│  step            2400 / 2903 (82.7%)                                                                       │
│  sim time        959.8 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.1146 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2998                                                                                    │
│  buffer          14011                                                                                     │
│  agent steps     14011                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 5 / 10                                                                          │
│  step            2800 / 2903 (96.5%)                                                                       │
│  sim time        1119.7 s                                                                                  │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -0.9384 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2997                                                                                    │
│  buffer          14411                                                                                     │
│  agent steps     14411                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 5 / 10                                                                          │
│  step            2903 / 2903 (100.0%)                                                                      │
│  sim time        1160.9 s                                                                                  │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -0.8930 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2996                                                                                    │
│  buffer          14514                                                                                     │
│  agent steps     14514                                                                                     │
│  status          episode done                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

warmup ep 5: 100%|██████████| 2903/2903 [01:14<00:00, 38.75step/s, reward=0.000, total=140.6]

Warmup:  50%|█████     | 5/10 [06:09<06:11, 74.22s/ep]

[run_serial] end mode=warmup steps=2903 total_reward=140.590923 avg_reward=0.048430

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 6 / 10                                                                          │
│  step            400 / 2903 (13.8%)                                                                        │
│  sim time        160.0 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  0.00                                                                                      │
│  body z angle    -2.2659 rad                                                                               │
│  omega sat       -0.0399 rad/s                                                                             │
│  image smear     1.890 px                                                                                  │
│  image quality   0.0880                                                                                    │
│  buffer          14914                                                                                     │
│  agent steps     14914                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 6 / 10                                                                          │
│  step            800 / 2903 (27.6%)                                                                        │
│  sim time        319.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  0.00                                                                                      │
│  body z angle    -2.2578 rad                                                                               │
│  omega sat       -0.0277 rad/s                                                                             │
│  image smear     1.522 px                                                                                  │
│  image quality   0.1011                                                                                    │
│  buffer          15314                                                                                     │
│  agent steps     15314                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 6 / 10                                                                          │
│  step            1200 / 2903 (41.3%)                                                                       │
│  sim time        479.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.5615 rad                                                                               │
│  omega sat       0.0014 rad/s                                                                              │
│  image smear     0.431 px                                                                                  │
│  image quality   0.3043                                                                                    │
│  buffer          15714                                                                                     │
│  agent steps     15714                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 6 / 10                                                                          │
│  step            1600 / 2903 (55.1%)                                                                       │
│  sim time        639.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.4670 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2999                                                                                    │
│  buffer          16114                                                                                     │
│  agent steps     16114                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 6 / 10                                                                          │
│  step            2000 / 2903 (68.9%)                                                                       │
│  sim time        799.8 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.2908 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2999                                                                                    │
│  buffer          16514                                                                                     │
│  agent steps     16514                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 6 / 10                                                                          │
│  step            2400 / 2903 (82.7%)                                                                       │
│  sim time        959.8 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.1146 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2998                                                                                    │
│  buffer          16914                                                                                     │
│  agent steps     16914                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 6 / 10                                                                          │
│  step            2800 / 2903 (96.5%)                                                                       │
│  sim time        1119.7 s                                                                                  │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -0.9384 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2997                                                                                    │
│  buffer          17314                                                                                     │
│  agent steps     17314                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 6 / 10                                                                          │
│  step            2903 / 2903 (100.0%)                                                                      │
│  sim time        1160.9 s                                                                                  │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -0.8930 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2996                                                                                    │
│  buffer          17417                                                                                     │
│  agent steps     17417                                                                                     │
│  status          episode done                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

warmup ep 6: 100%|██████████| 2903/2903 [01:16<00:00, 37.82step/s, reward=0.000, total=140.6]

Warmup:  60%|██████    | 6/10 [07:26<05:00, 75.10s/ep]

[run_serial] end mode=warmup steps=2903 total_reward=140.590923 avg_reward=0.048430

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 7 / 10                                                                          │
│  step            400 / 2903 (13.8%)                                                                        │
│  sim time        160.0 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  0.00                                                                                      │
│  body z angle    -2.2659 rad                                                                               │
│  omega sat       -0.0399 rad/s                                                                             │
│  image smear     1.890 px                                                                                  │
│  image quality   0.0880                                                                                    │
│  buffer          17817                                                                                     │
│  agent steps     17817                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 7 / 10                                                                          │
│  step            800 / 2903 (27.6%)                                                                        │
│  sim time        319.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  0.00                                                                                      │
│  body z angle    -2.2578 rad                                                                               │
│  omega sat       -0.0277 rad/s                                                                             │
│  image smear     1.522 px                                                                                  │
│  image quality   0.1011                                                                                    │
│  buffer          18217                                                                                     │
│  agent steps     18217                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 7 / 10                                                                          │
│  step            1200 / 2903 (41.3%)                                                                       │
│  sim time        479.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.5615 rad                                                                               │
│  omega sat       0.0014 rad/s                                                                              │
│  image smear     0.431 px                                                                                  │
│  image quality   0.3043                                                                                    │
│  buffer          18617                                                                                     │
│  agent steps     18617                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 7 / 10                                                                          │
│  step            1600 / 2903 (55.1%)                                                                       │
│  sim time        639.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.4670 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2999                                                                                    │
│  buffer          19017                                                                                     │
│  agent steps     19017                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 7 / 10                                                                          │
│  step            2000 / 2903 (68.9%)                                                                       │
│  sim time        799.8 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.2908 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2999                                                                                    │
│  buffer          19417                                                                                     │
│  agent steps     19417                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 7 / 10                                                                          │
│  step            2400 / 2903 (82.7%)                                                                       │
│  sim time        959.8 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.1146 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2998                                                                                    │
│  buffer          19817                                                                                     │
│  agent steps     19817                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 7 / 10                                                                          │
│  step            2800 / 2903 (96.5%)                                                                       │
│  sim time        1119.7 s                                                                                  │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -0.9384 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2997                                                                                    │
│  buffer          20217                                                                                     │
│  agent steps     20217                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 7 / 10                                                                          │
│  step            2903 / 2903 (100.0%)                                                                      │
│  sim time        1160.9 s                                                                                  │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -0.8930 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2996                                                                                    │
│  buffer          20320                                                                                     │
│  agent steps     20320                                                                                     │
│  status          episode done                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

warmup ep 7: 100%|██████████| 2903/2903 [01:21<00:00, 35.49step/s, reward=0.000, total=140.6]

Warmup:  70%|███████   | 7/10 [08:48<03:51, 77.31s/ep]

[run_serial] end mode=warmup steps=2903 total_reward=140.590923 avg_reward=0.048430

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 8 / 10                                                                          │
│  step            400 / 2903 (13.8%)                                                                        │
│  sim time        160.0 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  0.00                                                                                      │
│  body z angle    -2.2659 rad                                                                               │
│  omega sat       -0.0399 rad/s                                                                             │
│  image smear     1.890 px                                                                                  │
│  image quality   0.0880                                                                                    │
│  buffer          20720                                                                                     │
│  agent steps     20720                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 8 / 10                                                                          │
│  step            800 / 2903 (27.6%)                                                                        │
│  sim time        319.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  0.00                                                                                      │
│  body z angle    -2.2578 rad                                                                               │
│  omega sat       -0.0277 rad/s                                                                             │
│  image smear     1.522 px                                                                                  │
│  image quality   0.1011                                                                                    │
│  buffer          21120                                                                                     │
│  agent steps     21120                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 8 / 10                                                                          │
│  step            1200 / 2903 (41.3%)                                                                       │
│  sim time        479.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.5615 rad                                                                               │
│  omega sat       0.0014 rad/s                                                                              │
│  image smear     0.431 px                                                                                  │
│  image quality   0.3043                                                                                    │
│  buffer          21520                                                                                     │
│  agent steps     21520                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 8 / 10                                                                          │
│  step            1600 / 2903 (55.1%)                                                                       │
│  sim time        639.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.4670 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2999                                                                                    │
│  buffer          21920                                                                                     │
│  agent steps     21920                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 8 / 10                                                                          │
│  step            2000 / 2903 (68.9%)                                                                       │
│  sim time        799.8 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.2908 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2999                                                                                    │
│  buffer          22320                                                                                     │
│  agent steps     22320                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 8 / 10                                                                          │
│  step            2400 / 2903 (82.7%)                                                                       │
│  sim time        959.8 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.1146 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2998                                                                                    │
│  buffer          22720                                                                                     │
│  agent steps     22720                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 8 / 10                                                                          │
│  step            2800 / 2903 (96.5%)                                                                       │
│  sim time        1119.7 s                                                                                  │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -0.9384 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2997                                                                                    │
│  buffer          23120                                                                                     │
│  agent steps     23120                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 8 / 10                                                                          │
│  step            2903 / 2903 (100.0%)                                                                      │
│  sim time        1160.9 s                                                                                  │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -0.8930 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2996                                                                                    │
│  buffer          23223                                                                                     │
│  agent steps     23223                                                                                     │
│  status          episode done                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

warmup ep 8: 100%|██████████| 2903/2903 [01:23<00:00, 34.75step/s, reward=0.000, total=140.6]

Warmup:  80%|████████  | 8/10 [10:12<02:38, 79.31s/ep]

[run_serial] end mode=warmup steps=2903 total_reward=140.590923 avg_reward=0.048430

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 9 / 10                                                                          │
│  step            400 / 2903 (13.8%)                                                                        │
│  sim time        160.0 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  0.00                                                                                      │
│  body z angle    -2.2659 rad                                                                               │
│  omega sat       -0.0399 rad/s                                                                             │
│  image smear     1.890 px                                                                                  │
│  image quality   0.0880                                                                                    │
│  buffer          23623                                                                                     │
│  agent steps     23623                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 9 / 10                                                                          │
│  step            800 / 2903 (27.6%)                                                                        │
│  sim time        319.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  0.00                                                                                      │
│  body z angle    -2.2578 rad                                                                               │
│  omega sat       -0.0277 rad/s                                                                             │
│  image smear     1.522 px                                                                                  │
│  image quality   0.1011                                                                                    │
│  buffer          24023                                                                                     │
│  agent steps     24023                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 9 / 10                                                                          │
│  step            1200 / 2903 (41.3%)                                                                       │
│  sim time        479.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.5615 rad                                                                               │
│  omega sat       0.0014 rad/s                                                                              │
│  image smear     0.431 px                                                                                  │
│  image quality   0.3043                                                                                    │
│  buffer          24423                                                                                     │
│  agent steps     24423                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 9 / 10                                                                          │
│  step            1600 / 2903 (55.1%)                                                                       │
│  sim time        639.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.4670 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2999                                                                                    │
│  buffer          24823                                                                                     │
│  agent steps     24823                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 9 / 10                                                                          │
│  step            2000 / 2903 (68.9%)                                                                       │
│  sim time        799.8 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.2908 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2999                                                                                    │
│  buffer          25223                                                                                     │
│  agent steps     25223                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 9 / 10                                                                          │
│  step            2400 / 2903 (82.7%)                                                                       │
│  sim time        959.8 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.1146 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2998                                                                                    │
│  buffer          25623                                                                                     │
│  agent steps     25623                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 9 / 10                                                                          │
│  step            2800 / 2903 (96.5%)                                                                       │
│  sim time        1119.7 s                                                                                  │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -0.9384 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2997                                                                                    │
│  buffer          26023                                                                                     │
│  agent steps     26023                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 9 / 10                                                                          │
│  step            2903 / 2903 (100.0%)                                                                      │
│  sim time        1160.9 s                                                                                  │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -0.8930 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2996                                                                                    │
│  buffer          26126                                                                                     │
│  agent steps     26126                                                                                     │
│  status          episode done                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

warmup ep 9: 100%|██████████| 2903/2903 [01:22<00:00, 34.99step/s, reward=0.000, total=140.6]

Warmup:  90%|█████████ | 9/10 [11:35<01:20, 80.47s/ep]

[run_serial] end mode=warmup steps=2903 total_reward=140.590923 avg_reward=0.048430

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 10 / 10                                                                         │
│  step            400 / 2903 (13.8%)                                                                        │
│  sim time        160.0 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  0.00                                                                                      │
│  body z angle    -2.2659 rad                                                                               │
│  omega sat       -0.0399 rad/s                                                                             │
│  image smear     1.890 px                                                                                  │
│  image quality   0.0880                                                                                    │
│  buffer          26526                                                                                     │
│  agent steps     26526                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 10 / 10                                                                         │
│  step            800 / 2903 (27.6%)                                                                        │
│  sim time        319.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  0.00                                                                                      │
│  body z angle    -2.2578 rad                                                                               │
│  omega sat       -0.0277 rad/s                                                                             │
│  image smear     1.522 px                                                                                  │
│  image quality   0.1011                                                                                    │
│  buffer          26926                                                                                     │
│  agent steps     26926                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 10 / 10                                                                         │
│  step            1200 / 2903 (41.3%)                                                                       │
│  sim time        479.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.5615 rad                                                                               │
│  omega sat       0.0014 rad/s                                                                              │
│  image smear     0.431 px                                                                                  │
│  image quality   0.3043                                                                                    │
│  buffer          27326                                                                                     │
│  agent steps     27326                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 10 / 10                                                                         │
│  step            1600 / 2903 (55.1%)                                                                       │
│  sim time        639.9 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.4670 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2999                                                                                    │
│  buffer          27726                                                                                     │
│  agent steps     27726                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 10 / 10                                                                         │
│  step            2000 / 2903 (68.9%)                                                                       │
│  sim time        799.8 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.2908 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2999                                                                                    │
│  buffer          28126                                                                                     │
│  agent steps     28126                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 10 / 10                                                                         │
│  step            2400 / 2903 (82.7%)                                                                       │
│  sim time        959.8 s                                                                                   │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -1.1146 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2998                                                                                    │
│  buffer          28526                                                                                     │
│  agent steps     28526                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 10 / 10                                                                         │
│  step            2800 / 2903 (96.5%)                                                                       │
│  sim time        1119.7 s                                                                                  │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -0.9384 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2997                                                                                    │
│  buffer          28926                                                                                     │
│  agent steps     28926                                                                                     │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter       Value                                                                                     │
│  episode         warmup ep 10 / 10                                                                         │
│  step            2903 / 2903 (100.0%)                                                                      │
│  sim time        1160.9 s                                                                                  │
│  step reward     0.0000                                                                                    │
│  episode return  140.59                                                                                    │
│  body z angle    -0.8930 rad                                                                               │
│  omega sat       0.0011 rad/s                                                                              │
│  image smear     0.442 px                                                                                  │
│  image quality   0.2996                                                                                    │
│  buffer          29029                                                                                     │
│  agent steps     29029                                                                                     │
│  status          episode done                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

warmup ep 10: 100%|██████████| 2903/2903 [01:21<00:00, 35.56step/s, reward=0.000, total=140.6]

Warmup: 100%|██████████| 10/10 [12:56<00:00, 77.70s/ep]

[run_serial] end mode=warmup steps=2903 total_reward=140.590923 avg_reward=0.048430

Train:   0%|          | 0/5 [00:00<?, ?ep/s]

╭──────────────────────────────────────────────── Simulation info ────────────────────────────────────────────────╮
│  Parameter                                     Value                                                            │
│  episode duration                              1160.93 s                                                        │
│  simulation timestep                           0.399906 s                                                       │
│  integration steps                             2903 (+1 state samples)                                          │
│  orbit altitude                                528.76 km                                                        │
│  orbit period                                  5703.8 s                                                         │
│  theta center offset                           90.00 deg                                                        │
│  episode theta start (rel. center)             -32.693 deg                                                      │
│  episode theta end (rel. center)               37.091 deg                                                       │
│  sat motion span scale                         1.050                                                            │
│  sat z offset                                  0.00 deg                                                         │
│  target areas                                  50                                                               │
│  target phi stripe                             79.93 deg .. 104.46 deg                                          │
│  cloud patches                                 25                                                               │
│  render mode                                   headless                                                         │
│  torque command source                         external                                                         │
│  torque policy                                 MPOAgent:train                                                   │
│  attitude controller                           enabled                                                          │
│  control stack (display)                       MPOAgent:train · attitude_controller                             │
│  controller seed                               -                                                                │
│  controller update (configured)                1 s                                                              │
│  controller update (effective)                 0.8 s (2 steps)                                                  │
│  reaction-wheel torque max                     0.1000 N*m                                                       │
│  attitude safety cutoff                        |omega_sat| > 3.00 deg/s -> block opposing torque                │
│  camera kernel backend                         accelerated                                                      │
│  reward shaping                                outer_gate                                                       │
│  episode runner mode                           train                                                            │
│  agent                                         MPOAgent                                                         │
│  Camera 1 (primary) - role                     shapes reward (observation line + strip)                         │
│  Camera 1 (primary) - tilt off nadir           0.00 deg                                                         │
│  Camera 1 (primary) - FOV (cross x along)      1.61 deg x 1.20 deg                                              │
│  Camera 1 (primary) - resolution               9344 x 7000 px                                                   │
│  Camera 1 (primary) - pixel pitch              3.20 um                                                          │
│  Camera 1 (primary) - focal length             1067.0 mm                                                        │
│  Camera 1 (primary) - GSD @ 528.8 km           1.586 m                                                          │
│  Camera 1 (primary) - observation line bins    100                                                              │
│  Camera 1 (primary) - strip ray samples        96                                                               │
│  Camera 1 (primary) - sim vertical FOV         1.203 deg                                                        │
│  Camera 1 (primary) - exposure time            100 us (image smear)                                             │
│  Camera 2 (secondary) - role                   cloud/context only (no exposure in reward)                       │
│  Camera 2 (secondary) - tilt off nadir         25.00 deg                                                        │
│  Camera 2 (secondary) - FOV (cross x along)    102.45 deg x 70.00 deg                                           │
│  Camera 2 (secondary) - resolution             5312 x 2988 px                                                   │
│  Camera 2 (secondary) - pixel pitch            1.55 um                                                          │
│  Camera 2 (secondary) - focal length           3.3 mm                                                           │
│  Camera 2 (secondary) - GSD @ 528.8 km         247.818 m                                                        │
│  Camera 2 (secondary) - observation line bins  200                                                              │
│  Camera 2 (secondary) - sim vertical FOV       70.000 deg                                                       │
╰─────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               100 / 2903 (3.4%)                                                                      │
│  sim time           40.0 s                                                                                 │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.4685 rad                                                                            │
│  omega sat          -0.0240 rad/s                                                                          │
│  image smear        1.510 px                                                                               │
│  image quality      0.0901                                                                                 │
│  buffer             29129                                                                                  │
│  agent steps        29129                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       56958.717203                                                                           │
│  q loss (ep mean)   4.339321                                                                               │
│  pi loss (ep mean)  -0.576237                                                                              │
│  eta (ep mean)      2.896255                                                                               │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               200 / 2903 (6.9%)                                                                      │
│  sim time           80.0 s                                                                                 │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -2.0695 rad                                                                            │
│  omega sat          0.0100 rad/s                                                                           │
│  image smear        0.139 px                                                                               │
│  image quality      0.5765                                                                                 │
│  buffer             29229                                                                                  │
│  agent steps        29229                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       125709.645194                                                                          │
│  q loss (ep mean)   4.567300                                                                               │
│  pi loss (ep mean)  -0.723772                                                                              │
│  eta (ep mean)      3.157233                                                                               │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               300 / 2903 (10.3%)                                                                     │
│  sim time           120.0 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.4849 rad                                                                            │
│  omega sat          -0.0361 rad/s                                                                          │
│  image smear        1.935 px                                                                               │
│  image quality      0.0767                                                                                 │
│  buffer             29329                                                                                  │
│  agent steps        29329                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       149371.473463                                                                          │
│  q loss (ep mean)   4.008650                                                                               │
│  pi loss (ep mean)  -0.772600                                                                              │
│  eta (ep mean)      3.418015                                                                               │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               400 / 2903 (13.8%)                                                                     │
│  sim time           160.0 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.9262 rad                                                                            │
│  omega sat          0.0216 rad/s                                                                           │
│  image smear        0.257 px                                                                               │
│  image quality      0.4232                                                                                 │
│  buffer             29429                                                                                  │
│  agent steps        29429                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       162369.365688                                                                          │
│  q loss (ep mean)   4.089131                                                                               │
│  pi loss (ep mean)  -0.796969                                                                              │
│  eta (ep mean)      3.687211                                                                               │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               500 / 2903 (17.2%)                                                                     │
│  sim time           200.0 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.5519 rad                                                                            │
│  omega sat          -0.0449 rad/s                                                                          │
│  image smear        2.143 px                                                                               │
│  image quality      0.0752                                                                                 │
│  buffer             29529                                                                                  │
│  agent steps        29529                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       170456.511091                                                                          │
│  q loss (ep mean)   3.973578                                                                               │
│  pi loss (ep mean)  -0.811573                                                                              │
│  eta (ep mean)      3.977222                                                                               │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               600 / 2903 (20.7%)                                                                     │
│  sim time           239.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.7414 rad                                                                            │
│  omega sat          0.0331 rad/s                                                                           │
│  image smear        0.674 px                                                                               │
│  image quality      0.2168                                                                                 │
│  buffer             29629                                                                                  │
│  agent steps        29629                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       175751.262917                                                                          │
│  q loss (ep mean)   3.732885                                                                               │
│  pi loss (ep mean)  -0.821292                                                                              │
│  eta (ep mean)      4.294924                                                                               │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               700 / 2903 (24.1%)                                                                     │
│  sim time           279.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.6166 rad                                                                            │
│  omega sat          -0.0370 rad/s                                                                          │
│  image smear        1.781 px                                                                               │
│  image quality      0.0934                                                                                 │
│  buffer             29729                                                                                  │
│  agent steps        29729                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       180435.214463                                                                          │
│  q loss (ep mean)   3.460368                                                                               │
│  pi loss (ep mean)  -0.828237                                                                              │
│  eta (ep mean)      4.649552                                                                               │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               800 / 2903 (27.6%)                                                                     │
│  sim time           319.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.5151 rad                                                                            │
│  omega sat          0.0446 rad/s                                                                           │
│  image smear        1.156 px                                                                               │
│  image quality      0.1350                                                                                 │
│  buffer             29829                                                                                  │
│  agent steps        29829                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       183976.827620                                                                          │
│  q loss (ep mean)   3.228520                                                                               │
│  pi loss (ep mean)  -0.833441                                                                              │
│  eta (ep mean)      5.048627                                                                               │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               900 / 2903 (31.0%)                                                                     │
│  sim time           359.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.6427 rad                                                                            │
│  omega sat          -0.0256 rad/s                                                                          │
│  image smear        1.359 px                                                                               │
│  image quality      0.1212                                                                                 │
│  buffer             29929                                                                                  │
│  agent steps        29929                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       187365.416682                                                                          │
│  q loss (ep mean)   3.110893                                                                               │
│  pi loss (ep mean)  -0.837494                                                                              │
│  eta (ep mean)      5.502328                                                                               │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               1000 / 2903 (34.4%)                                                                    │
│  sim time           399.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.2575 rad                                                                            │
│  omega sat          0.0459 rad/s                                                                           │
│  image smear        1.390 px                                                                               │
│  image quality      0.1080                                                                                 │
│  buffer             30029                                                                                  │
│  agent steps        30029                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       190470.098633                                                                          │
│  q loss (ep mean)   2.918432                                                                               │
│  pi loss (ep mean)  -0.840730                                                                              │
│  eta (ep mean)      6.022089                                                                               │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               1100 / 2903 (37.9%)                                                                    │
│  sim time           439.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.6299 rad                                                                            │
│  omega sat          -0.0151 rad/s                                                                          │
│  image smear        0.995 px                                                                               │
│  image quality      0.1596                                                                                 │
│  buffer             30129                                                                                  │
│  agent steps        30129                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       193170.736183                                                                          │
│  q loss (ep mean)   2.675833                                                                               │
│  pi loss (ep mean)  -0.843379                                                                              │
│  eta (ep mean)      6.622015                                                                               │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               1200 / 2903 (41.3%)                                                                    │
│  sim time           479.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.0311 rad                                                                            │
│  omega sat          0.0344 rad/s                                                                           │
│  image smear        1.127 px                                                                               │
│  image quality      0.1208                                                                                 │
│  buffer             30229                                                                                  │
│  agent steps        30229                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       195497.861215                                                                          │
│  q loss (ep mean)   2.479160                                                                               │
│  pi loss (ep mean)  -0.845587                                                                              │
│  eta (ep mean)      7.315949                                                                               │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               1300 / 2903 (44.8%)                                                                    │
│  sim time           519.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.5786 rad                                                                            │
│  omega sat          -0.0052 rad/s                                                                          │
│  image smear        0.658 px                                                                               │
│  image quality      0.2231                                                                                 │
│  buffer             30329                                                                                  │
│  agent steps        30329                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       197815.898410                                                                          │
│  q loss (ep mean)   2.320678                                                                               │
│  pi loss (ep mean)  -0.847454                                                                              │
│  eta (ep mean)      8.121943                                                                               │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               1400 / 2903 (48.2%)                                                                    │
│  sim time           559.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.8463 rad                                                                            │
│  omega sat          0.0228 rad/s                                                                           │
│  image smear        0.752 px                                                                               │
│  image quality      0.1604                                                                                 │
│  buffer             30429                                                                                  │
│  agent steps        30429                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       199874.758736                                                                          │
│  q loss (ep mean)   2.173421                                                                               │
│  pi loss (ep mean)  -0.849057                                                                              │
│  eta (ep mean)      9.064329                                                                               │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               1500 / 2903 (51.7%)                                                                    │
│  sim time           599.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.5040 rad                                                                            │
│  omega sat          -0.0012 rad/s                                                                          │
│  image smear        0.520 px                                                                               │
│  image quality      0.2667                                                                                 │
│  buffer             30529                                                                                  │
│  agent steps        30529                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       201926.212665                                                                          │
│  q loss (ep mean)   2.046100                                                                               │
│  pi loss (ep mean)  -0.850442                                                                              │
│  eta (ep mean)      10.168837                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               1600 / 2903 (55.1%)                                                                    │
│  sim time           639.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.7030 rad                                                                            │
│  omega sat          0.0113 rad/s                                                                           │
│  image smear        0.233 px                                                                               │
│  image quality      0.3695                                                                                 │
│  buffer             30629                                                                                  │
│  agent steps        30629                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       203629.035659                                                                          │
│  q loss (ep mean)   1.934467                                                                               │
│  pi loss (ep mean)  -0.851653                                                                              │
│  eta (ep mean)      11.467316                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               1700 / 2903 (58.6%)                                                                    │
│  sim time           679.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.4207 rad                                                                            │
│  omega sat          0.0003 rad/s                                                                           │
│  image smear        0.469 px                                                                               │
│  image quality      0.2874                                                                                 │
│  buffer             30729                                                                                  │
│  agent steps        30729                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       205201.515397                                                                          │
│  q loss (ep mean)   1.848792                                                                               │
│  pi loss (ep mean)  -0.852722                                                                              │
│  eta (ep mean)      12.994273                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               1800 / 2903 (62.0%)                                                                    │
│  sim time           719.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.6012 rad                                                                            │
│  omega sat          -0.0002 rad/s                                                                          │
│  image smear        0.388 px                                                                               │
│  image quality      0.2577                                                                                 │
│  buffer             30829                                                                                  │
│  agent steps        30829                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       206753.668802                                                                          │
│  q loss (ep mean)   1.760302                                                                               │
│  pi loss (ep mean)  -0.853672                                                                              │
│  eta (ep mean)      14.801247                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               1900 / 2903 (65.4%)                                                                    │
│  sim time           759.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.3343 rad                                                                            │
│  omega sat          0.0008 rad/s                                                                           │
│  image smear        0.451 px                                                                               │
│  image quality      0.2957                                                                                 │
│  buffer             30929                                                                                  │
│  agent steps        30929                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       208149.770127                                                                          │
│  q loss (ep mean)   1.678902                                                                               │
│  pi loss (ep mean)  -0.854523                                                                              │
│  eta (ep mean)      16.947070                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               2000 / 2903 (68.9%)                                                                    │
│  sim time           799.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.5410 rad                                                                            │
│  omega sat          -0.0118 rad/s                                                                          │
│  image smear        1.004 px                                                                               │
│  image quality      0.1212                                                                                 │
│  buffer             31029                                                                                  │
│  agent steps        31029                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       209654.043242                                                                          │
│  q loss (ep mean)   1.603510                                                                               │
│  pi loss (ep mean)  -0.855290                                                                              │
│  eta (ep mean)      19.500170                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               2100 / 2903 (72.3%)                                                                    │
│  sim time           839.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.2467 rad                                                                            │
│  omega sat          0.0010 rad/s                                                                           │
│  image smear        0.444 px                                                                               │
│  image quality      0.2987                                                                                 │
│  buffer             31129                                                                                  │
│  agent steps        31129                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       211097.198556                                                                          │
│  q loss (ep mean)   1.532757                                                                               │
│  pi loss (ep mean)  -0.855983                                                                              │
│  eta (ep mean)      22.559076                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               2200 / 2903 (75.8%)                                                                    │
│  sim time           879.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.5222 rad                                                                            │
│  omega sat          -0.0233 rad/s                                                                          │
│  image smear        1.519 px                                                                               │
│  image quality      0.0882                                                                                 │
│  buffer             31229                                                                                  │
│  agent steps        31229                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       212479.534037                                                                          │
│  q loss (ep mean)   1.471302                                                                               │
│  pi loss (ep mean)  -0.856616                                                                              │
│  eta (ep mean)      26.229605                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               2300 / 2903 (79.2%)                                                                    │
│  sim time           919.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.1480 rad                                                                            │
│  omega sat          0.0087 rad/s                                                                           │
│  image smear        0.182 px                                                                               │
│  image quality      0.5102                                                                                 │
│  buffer             31329                                                                                  │
│  agent steps        31329                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       213869.561856                                                                          │
│  q loss (ep mean)   1.413863                                                                               │
│  pi loss (ep mean)  -0.857189                                                                              │
│  eta (ep mean)      30.637224                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               2400 / 2903 (82.7%)                                                                    │
│  sim time           959.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.5450 rad                                                                            │
│  omega sat          -0.0348 rad/s                                                                          │
│  image smear        1.911 px                                                                               │
│  image quality      0.0770                                                                                 │
│  buffer             31429                                                                                  │
│  agent steps        31429                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       215238.422521                                                                          │
│  q loss (ep mean)   1.364379                                                                               │
│  pi loss (ep mean)  -0.857715                                                                              │
│  eta (ep mean)      35.942551                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               2500 / 2903 (86.1%)                                                                    │
│  sim time           999.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.0093 rad                                                                            │
│  omega sat          0.0203 rad/s                                                                           │
│  image smear        0.211 px                                                                               │
│  image quality      0.4717                                                                                 │
│  buffer             31529                                                                                  │
│  agent steps        31529                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       216648.666274                                                                          │
│  q loss (ep mean)   1.318524                                                                               │
│  pi loss (ep mean)  -0.858199                                                                              │
│  eta (ep mean)      42.366829                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               2600 / 2903 (89.6%)                                                                    │
│  sim time           1039.8 s                                                                               │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.6084 rad                                                                            │
│  omega sat          -0.0448 rad/s                                                                          │
│  image smear        2.157 px                                                                               │
│  image quality      0.0742                                                                                 │
│  buffer             31629                                                                                  │
│  agent steps        31629                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       217967.917770                                                                          │
│  q loss (ep mean)   1.278979                                                                               │
│  pi loss (ep mean)  -0.858646                                                                              │
│  eta (ep mean)      50.152650                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               2700 / 2903 (93.0%)                                                                    │
│  sim time           1079.7 s                                                                               │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.8291 rad                                                                            │
│  omega sat          0.0318 rad/s                                                                           │
│  image smear        0.619 px                                                                               │
│  image quality      0.2321                                                                                 │
│  buffer             31729                                                                                  │
│  agent steps        31729                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       219196.958093                                                                          │
│  q loss (ep mean)   1.240673                                                                               │
│  pi loss (ep mean)  -0.859061                                                                              │
│  eta (ep mean)      59.580627                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               2800 / 2903 (96.5%)                                                                    │
│  sim time           1119.7 s                                                                               │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.6762 rad                                                                            │
│  omega sat          -0.0383 rad/s                                                                          │
│  image smear        1.821 px                                                                               │
│  image quality      0.0912                                                                                 │
│  buffer             31829                                                                                  │
│  agent steps        31829                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       220482.326585                                                                          │
│  q loss (ep mean)   1.201577                                                                               │
│  pi loss (ep mean)  -0.859446                                                                              │
│  eta (ep mean)      71.028326                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               2900 / 2903 (99.9%)                                                                    │
│  sim time           1159.7 s                                                                               │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.6074 rad                                                                            │
│  omega sat          0.0434 rad/s                                                                           │
│  image smear        1.081 px                                                                               │
│  image quality      0.1437                                                                                 │
│  buffer             31929                                                                                  │
│  agent steps        31929                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       221574.177352                                                                          │
│  q loss (ep mean)   1.171166                                                                               │
│  pi loss (ep mean)  -0.859804                                                                              │
│  eta (ep mean)      84.939150                                                                              │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 1 / 5                                                                         │
│  step               2903 / 2903 (100.0%)                                                                   │
│  sim time           1160.9 s                                                                               │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.5523 rad                                                                            │
│  omega sat          0.0472 rad/s                                                                           │
│  image smear        1.263 px                                                                               │
│  image quality      0.1237                                                                                 │
│  buffer             31932                                                                                  │
│  agent steps        31932                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       221612.345242                                                                          │
│  q loss (ep mean)   1.170142                                                                               │
│  pi loss (ep mean)  -0.859815                                                                              │
│  eta (ep mean)      85.399931                                                                              │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 1: 100%|██████████| 2903/2903 [27:59<00:00,  1.73step/s, reward=0.000, total=0.0]

Train:  20%|██        | 1/5 [28:00<1:52:00, 1680.05s/ep, kl=221636.3246, reward=0.0]

[run_serial] end mode=train steps=2903 total_reward=0.000000 avg_reward=0.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               100 / 2903 (3.4%)                                                                      │
│  sim time           40.0 s                                                                                 │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.4594 rad                                                                            │
│  omega sat          -0.0256 rad/s                                                                          │
│  image smear        1.596 px                                                                               │
│  image quality      0.0851                                                                                 │
│  buffer             32032                                                                                  │
│  agent steps        32032                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       253830.444444                                                                          │
│  q loss (ep mean)   0.307402                                                                               │
│  pi loss (ep mean)  -0.869863                                                                              │
│  eta (ep mean)      596.911395                                                                             │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               200 / 2903 (6.9%)                                                                      │
│  sim time           80.0 s                                                                                 │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -2.0656 rad                                                                            │
│  omega sat          0.0113 rad/s                                                                           │
│  image smear        0.095 px                                                                               │
│  image quality      0.6660                                                                                 │
│  buffer             32132                                                                                  │
│  agent steps        32132                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       255521.903580                                                                          │
│  q loss (ep mean)   0.265414                                                                               │
│  pi loss (ep mean)  -0.869855                                                                              │
│  eta (ep mean)      672.015598                                                                             │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               300 / 2903 (10.3%)                                                                     │
│  sim time           120.0 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.4997 rad                                                                            │
│  omega sat          -0.0374 rad/s                                                                          │
│  image smear        1.972 px                                                                               │
│  image quality      0.0760                                                                                 │
│  buffer             32232                                                                                  │
│  agent steps        32232                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       256406.694084                                                                          │
│  q loss (ep mean)   0.280612                                                                               │
│  pi loss (ep mean)  -0.869850                                                                              │
│  eta (ep mean)      759.557870                                                                             │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               400 / 2903 (13.8%)                                                                     │
│  sim time           160.0 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.9175 rad                                                                            │
│  omega sat          0.0228 rad/s                                                                           │
│  image smear        0.302 px                                                                               │
│  image quality      0.3846                                                                                 │
│  buffer             32332                                                                                  │
│  agent steps        32332                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       258124.264450                                                                          │
│  q loss (ep mean)   0.281634                                                                               │
│  pi loss (ep mean)  -0.869840                                                                              │
│  eta (ep mean)      863.059783                                                                             │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               500 / 2903 (17.2%)                                                                     │
│  sim time           200.0 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.5702 rad                                                                            │
│  omega sat          -0.0446 rad/s                                                                          │
│  image smear        2.120 px                                                                               │
│  image quality      0.0765                                                                                 │
│  buffer             32432                                                                                  │
│  agent steps        32432                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       258466.284914                                                                          │
│  q loss (ep mean)   0.296058                                                                               │
│  pi loss (ep mean)  -0.869825                                                                              │
│  eta (ep mean)      985.192258                                                                             │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               600 / 2903 (20.7%)                                                                     │
│  sim time           239.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.7281 rad                                                                            │
│  omega sat          0.0344 rad/s                                                                           │
│  image smear        0.723 px                                                                               │
│  image quality      0.2048                                                                                 │
│  buffer             32532                                                                                  │
│  agent steps        32532                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       259646.515625                                                                          │
│  q loss (ep mean)   0.283513                                                                               │
│  pi loss (ep mean)  -0.869825                                                                              │
│  eta (ep mean)      1129.137991                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               700 / 2903 (24.1%)                                                                     │
│  sim time           279.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.6313 rad                                                                            │
│  omega sat          -0.0358 rad/s                                                                          │
│  image smear        1.731 px                                                                               │
│  image quality      0.0961                                                                                 │
│  buffer             32632                                                                                  │
│  agent steps        32632                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       260306.351104                                                                          │
│  q loss (ep mean)   0.263241                                                                               │
│  pi loss (ep mean)  -0.869827                                                                              │
│  eta (ep mean)      1299.942046                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               800 / 2903 (27.6%)                                                                     │
│  sim time           319.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.4972 rad                                                                            │
│  omega sat          0.0459 rad/s                                                                           │
│  image smear        1.217 px                                                                               │
│  image quality      0.1285                                                                                 │
│  buffer             32732                                                                                  │
│  agent steps        32732                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       260996.252855                                                                          │
│  q loss (ep mean)   0.242542                                                                               │
│  pi loss (ep mean)  -0.869824                                                                              │
│  eta (ep mean)      1502.494209                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               900 / 2903 (31.0%)                                                                     │
│  sim time           359.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.6529 rad                                                                            │
│  omega sat          -0.0244 rad/s                                                                          │
│  image smear        1.317 px                                                                               │
│  image quality      0.1248                                                                                 │
│  buffer             32832                                                                                  │
│  agent steps        32832                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       261972.012931                                                                          │
│  q loss (ep mean)   0.231497                                                                               │
│  pi loss (ep mean)  -0.869825                                                                              │
│  eta (ep mean)      1743.722641                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               1000 / 2903 (34.4%)                                                                    │
│  sim time           399.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.2401 rad                                                                            │
│  omega sat          0.0446 rad/s                                                                           │
│  image smear        1.364 px                                                                               │
│  image quality      0.1090                                                                                 │
│  buffer             32932                                                                                  │
│  agent steps        32932                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       263052.079001                                                                          │
│  q loss (ep mean)   0.227441                                                                               │
│  pi loss (ep mean)  -0.869822                                                                              │
│  eta (ep mean)      2032.916745                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               1100 / 2903 (37.9%)                                                                    │
│  sim time           439.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.6359 rad                                                                            │
│  omega sat          -0.0138 rad/s                                                                          │
│  image smear        0.951 px                                                                               │
│  image quality      0.1658                                                                                 │
│  buffer             33032                                                                                  │
│  agent steps        33032                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       263835.213418                                                                          │
│  q loss (ep mean)   0.218786                                                                               │
│  pi loss (ep mean)  -0.869822                                                                              │
│  eta (ep mean)      2379.498943                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               1200 / 2903 (41.3%)                                                                    │
│  sim time           479.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.0183 rad                                                                            │
│  omega sat          0.0331 rad/s                                                                           │
│  image smear        1.091 px                                                                               │
│  image quality      0.1233                                                                                 │
│  buffer             33132                                                                                  │
│  agent steps        33132                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       264546.159325                                                                          │
│  q loss (ep mean)   0.209462                                                                               │
│  pi loss (ep mean)  -0.869829                                                                              │
│  eta (ep mean)      2794.181751                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               1300 / 2903 (44.8%)                                                                    │
│  sim time           519.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.5808 rad                                                                            │
│  omega sat          -0.0046 rad/s                                                                          │
│  image smear        0.636 px                                                                               │
│  image quality      0.2293                                                                                 │
│  buffer             33232                                                                                  │
│  agent steps        33232                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       265605.390709                                                                          │
│  q loss (ep mean)   0.214079                                                                               │
│  pi loss (ep mean)  -0.869828                                                                              │
│  eta (ep mean)      3292.673943                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               1400 / 2903 (48.2%)                                                                    │
│  sim time           559.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.8381 rad                                                                            │
│  omega sat          0.0216 rad/s                                                                           │
│  image smear        0.701 px                                                                               │
│  image quality      0.1690                                                                                 │
│  buffer             33332                                                                                  │
│  agent steps        33332                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       266225.680587                                                                          │
│  q loss (ep mean)   0.225044                                                                               │
│  pi loss (ep mean)  -0.869826                                                                              │
│  eta (ep mean)      3893.629500                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               1500 / 2903 (51.7%)                                                                    │
│  sim time           599.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.5048 rad                                                                            │
│  omega sat          -0.0009 rad/s                                                                          │
│  image smear        0.512 px                                                                               │
│  image quality      0.2699                                                                                 │
│  buffer             33432                                                                                  │
│  agent steps        33432                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       266707.208087                                                                          │
│  q loss (ep mean)   0.222962                                                                               │
│  pi loss (ep mean)  -0.869826                                                                              │
│  eta (ep mean)      4614.435204                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               1600 / 2903 (55.1%)                                                                    │
│  sim time           639.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.6994 rad                                                                            │
│  omega sat          0.0100 rad/s                                                                           │
│  image smear        0.168 px                                                                               │
│  image quality      0.4483                                                                                 │
│  buffer             33532                                                                                  │
│  agent steps        33532                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       267688.855466                                                                          │
│  q loss (ep mean)   0.214278                                                                               │
│  pi loss (ep mean)  -0.869827                                                                              │
│  eta (ep mean)      5484.971343                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               1700 / 2903 (58.6%)                                                                    │
│  sim time           679.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.4210 rad                                                                            │
│  omega sat          0.0004 rad/s                                                                           │
│  image smear        0.466 px                                                                               │
│  image quality      0.2888                                                                                 │
│  buffer             33632                                                                                  │
│  agent steps        33632                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       269164.900318                                                                          │
│  q loss (ep mean)   0.205302                                                                               │
│  pi loss (ep mean)  -0.869827                                                                              │
│  eta (ep mean)      6546.717970                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               1800 / 2903 (62.0%)                                                                    │
│  sim time           719.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.6023 rad                                                                            │
│  omega sat          -0.0015 rad/s                                                                          │
│  image smear        0.459 px                                                                               │
│  image quality      0.2271                                                                                 │
│  buffer             33732                                                                                  │
│  agent steps        33732                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       270717.246691                                                                          │
│  q loss (ep mean)   0.199930                                                                               │
│  pi loss (ep mean)  -0.869826                                                                              │
│  eta (ep mean)      7844.239316                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               1900 / 2903 (65.4%)                                                                    │
│  sim time           759.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.3344 rad                                                                            │
│  omega sat          0.0009 rad/s                                                                           │
│  image smear        0.450 px                                                                               │
│  image quality      0.2962                                                                                 │
│  buffer             33832                                                                                  │
│  agent steps        33832                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       272358.724139                                                                          │
│  q loss (ep mean)   0.198339                                                                               │
│  pi loss (ep mean)  -0.869826                                                                              │
│  eta (ep mean)      9432.704986                                                                            │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               2000 / 2903 (68.9%)                                                                    │
│  sim time           799.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.5466 rad                                                                            │
│  omega sat          -0.0130 rad/s                                                                          │
│  image smear        1.068 px                                                                               │
│  image quality      0.1153                                                                                 │
│  buffer             33932                                                                                  │
│  agent steps        33932                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       273839.970712                                                                          │
│  q loss (ep mean)   0.202720                                                                               │
│  pi loss (ep mean)  -0.869828                                                                              │
│  eta (ep mean)      11373.243082                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               2100 / 2903 (72.3%)                                                                    │
│  sim time           839.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.2467 rad                                                                            │
│  omega sat          0.0010 rad/s                                                                           │
│  image smear        0.444 px                                                                               │
│  image quality      0.2988                                                                                 │
│  buffer             34032                                                                                  │
│  agent steps        34032                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       275861.927577                                                                          │
│  q loss (ep mean)   0.207768                                                                               │
│  pi loss (ep mean)  -0.869827                                                                              │
│  eta (ep mean)      13753.263496                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               2200 / 2903 (75.8%)                                                                    │
│  sim time           879.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.5325 rad                                                                            │
│  omega sat          -0.0246 rad/s                                                                          │
│  image smear        1.569 px                                                                               │
│  image quality      0.0863                                                                                 │
│  buffer             34132                                                                                  │
│  agent steps        34132                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       277754.178710                                                                          │
│  q loss (ep mean)   0.204203                                                                               │
│  pi loss (ep mean)  -0.869827                                                                              │
│  eta (ep mean)      16680.813768                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               2300 / 2903 (79.2%)                                                                    │
│  sim time           919.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.1444 rad                                                                            │
│  omega sat          0.0100 rad/s                                                                           │
│  image smear        0.138 px                                                                               │
│  image quality      0.5782                                                                                 │
│  buffer             34232                                                                                  │
│  agent steps        34232                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       279308.335778                                                                          │
│  q loss (ep mean)   0.202177                                                                               │
│  pi loss (ep mean)  -0.869826                                                                              │
│  eta (ep mean)      20266.787054                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               2400 / 2903 (82.7%)                                                                    │
│  sim time           959.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.5599 rad                                                                            │
│  omega sat          -0.0361 rad/s                                                                          │
│  image smear        1.948 px                                                                               │
│  image quality      0.0762                                                                                 │
│  buffer             34332                                                                                  │
│  agent steps        34332                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       280766.652212                                                                          │
│  q loss (ep mean)   0.200597                                                                               │
│  pi loss (ep mean)  -0.869827                                                                              │
│  eta (ep mean)      24647.561777                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               2500 / 2903 (86.1%)                                                                    │
│  sim time           999.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.0011 rad                                                                            │
│  omega sat          0.0216 rad/s                                                                           │
│  image smear        0.256 px                                                                               │
│  image quality      0.4245                                                                                 │
│  buffer             34432                                                                                  │
│  agent steps        34432                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       282123.195197                                                                          │
│  q loss (ep mean)   0.198662                                                                               │
│  pi loss (ep mean)  -0.869827                                                                              │
│  eta (ep mean)      29994.120185                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               2600 / 2903 (89.6%)                                                                    │
│  sim time           1039.8 s                                                                               │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.6268 rad                                                                            │
│  omega sat          -0.0449 rad/s                                                                          │
│  image smear        2.143 px                                                                               │
│  image quality      0.0752                                                                                 │
│  buffer             34532                                                                                  │
│  agent steps        34532                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       283788.957790                                                                          │
│  q loss (ep mean)   0.223412                                                                               │
│  pi loss (ep mean)  -0.869827                                                                              │
│  eta (ep mean)      36549.282650                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               2700 / 2903 (93.0%)                                                                    │
│  sim time           1079.7 s                                                                               │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.8163 rad                                                                            │
│  omega sat          0.0331 rad/s                                                                           │
│  image smear        0.667 px                                                                               │
│  image quality      0.2187                                                                                 │
│  buffer             34632                                                                                  │
│  agent steps        34632                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       285214.577778                                                                          │
│  q loss (ep mean)   0.222499                                                                               │
│  pi loss (ep mean)  -0.869827                                                                              │
│  eta (ep mean)      44606.235509                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               2800 / 2903 (96.5%)                                                                    │
│  sim time           1119.7 s                                                                               │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.6914 rad                                                                            │
│  omega sat          -0.0370 rad/s                                                                          │
│  image smear        1.771 px                                                                               │
│  image quality      0.0939                                                                                 │
│  buffer             34732                                                                                  │
│  agent steps        34732                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       286625.425258                                                                          │
│  q loss (ep mean)   0.229239                                                                               │
│  pi loss (ep mean)  -0.869826                                                                              │
│  eta (ep mean)      54491.379560                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               2900 / 2903 (99.9%)                                                                    │
│  sim time           1159.7 s                                                                               │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.5900 rad                                                                            │
│  omega sat          0.0446 rad/s                                                                           │
│  image smear        1.140 px                                                                               │
│  image quality      0.1367                                                                                 │
│  buffer             34832                                                                                  │
│  agent steps        34832                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       287877.883155                                                                          │
│  q loss (ep mean)   0.240159                                                                               │
│  pi loss (ep mean)  -0.869827                                                                              │
│  eta (ep mean)      66616.602433                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 2 / 5                                                                         │
│  step               2903 / 2903 (100.0%)                                                                   │
│  sim time           1160.9 s                                                                               │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.5333 rad                                                                            │
│  omega sat          0.0485 rad/s                                                                           │
│  image smear        1.329 px                                                                               │
│  image quality      0.1176                                                                                 │
│  buffer             34835                                                                                  │
│  agent steps        34835                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       287928.366520                                                                          │
│  q loss (ep mean)   0.239998                                                                               │
│  pi loss (ep mean)  -0.869827                                                                              │
│  eta (ep mean)      67020.083471                                                                           │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 2: 100%|██████████| 2903/2903 [29:39<00:00,  1.63step/s, reward=0.000, total=0.0]

Train:  40%|████      | 2/5 [57:39<1:26:55, 1738.63s/ep, kl=287936.8924, reward=0.0]

[run_serial] end mode=train steps=2903 total_reward=0.000000 avg_reward=0.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               100 / 2903 (3.4%)                                                                      │
│  sim time           40.0 s                                                                                 │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.4594 rad                                                                            │
│  omega sat          -0.0256 rad/s                                                                          │
│  image smear        1.596 px                                                                               │
│  image quality      0.0851                                                                                 │
│  buffer             34935                                                                                  │
│  agent steps        34935                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       319771.070707                                                                          │
│  q loss (ep mean)   0.311967                                                                               │
│  pi loss (ep mean)  -0.869828                                                                              │
│  eta (ep mean)      516157.936237                                                                          │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               200 / 2903 (6.9%)                                                                      │
│  sim time           80.0 s                                                                                 │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -2.0656 rad                                                                            │
│  omega sat          0.0113 rad/s                                                                           │
│  image smear        0.095 px                                                                               │
│  image quality      0.6660                                                                                 │
│  buffer             35035                                                                                  │
│  agent steps        35035                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       319928.324435                                                                          │
│  q loss (ep mean)   0.579270                                                                               │
│  pi loss (ep mean)  -0.869821                                                                              │
│  eta (ep mean)      583357.625628                                                                          │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               300 / 2903 (10.3%)                                                                     │
│  sim time           120.0 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.4997 rad                                                                            │
│  omega sat          -0.0374 rad/s                                                                          │
│  image smear        1.972 px                                                                               │
│  image quality      0.0760                                                                                 │
│  buffer             35135                                                                                  │
│  agent steps        35135                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       320291.975439                                                                          │
│  q loss (ep mean)   0.532993                                                                               │
│  pi loss (ep mean)  -0.869828                                                                              │
│  eta (ep mean)      661886.187082                                                                          │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               400 / 2903 (13.8%)                                                                     │
│  sim time           160.0 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.9175 rad                                                                            │
│  omega sat          0.0228 rad/s                                                                           │
│  image smear        0.302 px                                                                               │
│  image quality      0.3846                                                                                 │
│  buffer             35235                                                                                  │
│  agent steps        35235                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       321012.730420                                                                          │
│  q loss (ep mean)   0.465876                                                                               │
│  pi loss (ep mean)  -0.869833                                                                              │
│  eta (ep mean)      754460.042920                                                                          │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               500 / 2903 (17.2%)                                                                     │
│  sim time           200.0 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.5702 rad                                                                            │
│  omega sat          -0.0446 rad/s                                                                          │
│  image smear        2.120 px                                                                               │
│  image quality      0.0765                                                                                 │
│  buffer             35335                                                                                  │
│  agent steps        35335                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       320518.250501                                                                          │
│  q loss (ep mean)   0.390499                                                                               │
│  pi loss (ep mean)  -0.869828                                                                              │
│  eta (ep mean)      863893.278307                                                                          │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               600 / 2903 (20.7%)                                                                     │
│  sim time           239.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.7281 rad                                                                            │
│  omega sat          0.0344 rad/s                                                                           │
│  image smear        0.723 px                                                                               │
│  image quality      0.2048                                                                                 │
│  buffer             35435                                                                                  │
│  agent steps        35435                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       320547.991288                                                                          │
│  q loss (ep mean)   0.336777                                                                               │
│  pi loss (ep mean)  -0.869828                                                                              │
│  eta (ep mean)      992865.395242                                                                          │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               700 / 2903 (24.1%)                                                                     │
│  sim time           279.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.6313 rad                                                                            │
│  omega sat          -0.0358 rad/s                                                                          │
│  image smear        1.731 px                                                                               │
│  image quality      0.0961                                                                                 │
│  buffer             35535                                                                                  │
│  agent steps        35535                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       321211.028299                                                                          │
│  q loss (ep mean)   0.432214                                                                               │
│  pi loss (ep mean)  -0.869830                                                                              │
│  eta (ep mean)      1146356.569921                                                                         │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               800 / 2903 (27.6%)                                                                     │
│  sim time           319.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.4972 rad                                                                            │
│  omega sat          0.0459 rad/s                                                                           │
│  image smear        1.217 px                                                                               │
│  image quality      0.1285                                                                                 │
│  buffer             35635                                                                                  │
│  agent steps        35635                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       322319.162840                                                                          │
│  q loss (ep mean)   0.399585                                                                               │
│  pi loss (ep mean)  -0.869827                                                                              │
│  eta (ep mean)      1329653.668179                                                                         │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               900 / 2903 (31.0%)                                                                     │
│  sim time           359.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.6529 rad                                                                            │
│  omega sat          -0.0244 rad/s                                                                          │
│  image smear        1.317 px                                                                               │
│  image quality      0.1248                                                                                 │
│  buffer             35735                                                                                  │
│  agent steps        35735                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       322552.992474                                                                          │
│  q loss (ep mean)   0.362906                                                                               │
│  pi loss (ep mean)  -0.869830                                                                              │
│  eta (ep mean)      1548687.983454                                                                         │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               1000 / 2903 (34.4%)                                                                    │
│  sim time           399.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.2401 rad                                                                            │
│  omega sat          0.0446 rad/s                                                                           │
│  image smear        1.364 px                                                                               │
│  image quality      0.1090                                                                                 │
│  buffer             35835                                                                                  │
│  agent steps        35835                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       325086.338729                                                                          │
│  q loss (ep mean)   0.363055                                                                               │
│  pi loss (ep mean)  -0.869830                                                                              │
│  eta (ep mean)      1812090.677803                                                                         │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               1100 / 2903 (37.9%)                                                                    │
│  sim time           439.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.6359 rad                                                                            │
│  omega sat          -0.0138 rad/s                                                                          │
│  image smear        0.951 px                                                                               │
│  image quality      0.1658                                                                                 │
│  buffer             35935                                                                                  │
│  agent steps        35935                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       327529.790449                                                                          │
│  q loss (ep mean)   0.338486                                                                               │
│  pi loss (ep mean)  -0.869830                                                                              │
│  eta (ep mean)      2132827.763990                                                                         │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               1200 / 2903 (41.3%)                                                                    │
│  sim time           479.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.0183 rad                                                                            │
│  omega sat          0.0331 rad/s                                                                           │
│  image smear        1.091 px                                                                               │
│  image quality      0.1233                                                                                 │
│  buffer             36035                                                                                  │
│  agent steps        36035                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       329148.204793                                                                          │
│  q loss (ep mean)   0.315976                                                                               │
│  pi loss (ep mean)  -0.869829                                                                              │
│  eta (ep mean)      2520018.647727                                                                         │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               1300 / 2903 (44.8%)                                                                    │
│  sim time           519.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.5808 rad                                                                            │
│  omega sat          -0.0046 rad/s                                                                          │
│  image smear        0.636 px                                                                               │
│  image quality      0.2293                                                                                 │
│  buffer             36135                                                                                  │
│  agent steps        36135                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       330545.304597                                                                          │
│  q loss (ep mean)   0.305122                                                                               │
│  pi loss (ep mean)  -0.869827                                                                              │
│  eta (ep mean)      2986664.705254                                                                         │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               1400 / 2903 (48.2%)                                                                    │
│  sim time           559.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.8381 rad                                                                            │
│  omega sat          0.0216 rad/s                                                                           │
│  image smear        0.701 px                                                                               │
│  image quality      0.1690                                                                                 │
│  buffer             36235                                                                                  │
│  agent steps        36235                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       332319.465344                                                                          │
│  q loss (ep mean)   0.286538                                                                               │
│  pi loss (ep mean)  -0.869827                                                                              │
│  eta (ep mean)      3550457.145908                                                                         │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               1500 / 2903 (51.7%)                                                                    │
│  sim time           599.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.5048 rad                                                                            │
│  omega sat          -0.0009 rad/s                                                                          │
│  image smear        0.512 px                                                                               │
│  image quality      0.2699                                                                                 │
│  buffer             36335                                                                                  │
│  agent steps        36335                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       333427.649235                                                                          │
│  q loss (ep mean)   0.276382                                                                               │
│  pi loss (ep mean)  -0.869829                                                                              │
│  eta (ep mean)      4230986.372332                                                                         │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               1600 / 2903 (55.1%)                                                                    │
│  sim time           639.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.6994 rad                                                                            │
│  omega sat          0.0100 rad/s                                                                           │
│  image smear        0.168 px                                                                               │
│  image quality      0.4483                                                                                 │
│  buffer             36435                                                                                  │
│  agent steps        36435                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       334334.997176                                                                          │
│  q loss (ep mean)   0.275658                                                                               │
│  pi loss (ep mean)  -0.869833                                                                              │
│  eta (ep mean)      5050760.155175                                                                         │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               1700 / 2903 (58.6%)                                                                    │
│  sim time           679.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.4210 rad                                                                            │
│  omega sat          0.0004 rad/s                                                                           │
│  image smear        0.466 px                                                                               │
│  image quality      0.2888                                                                                 │
│  buffer             36535                                                                                  │
│  agent steps        36535                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       334863.849663                                                                          │
│  q loss (ep mean)   0.267459                                                                               │
│  pi loss (ep mean)  -0.869832                                                                              │
│  eta (ep mean)      6039932.922969                                                                         │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               1800 / 2903 (62.0%)                                                                    │
│  sim time           719.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.6023 rad                                                                            │
│  omega sat          -0.0015 rad/s                                                                          │
│  image smear        0.459 px                                                                               │
│  image quality      0.2271                                                                                 │
│  buffer             36635                                                                                  │
│  agent steps        36635                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       335990.834031                                                                          │
│  q loss (ep mean)   0.262114                                                                               │
│  pi loss (ep mean)  -0.869832                                                                              │
│  eta (ep mean)      7236878.214633                                                                         │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               1900 / 2903 (65.4%)                                                                    │
│  sim time           759.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.3344 rad                                                                            │
│  omega sat          0.0009 rad/s                                                                           │
│  image smear        0.450 px                                                                               │
│  image quality      0.2962                                                                                 │
│  buffer             36735                                                                                  │
│  agent steps        36735                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       337544.597477                                                                          │
│  q loss (ep mean)   0.265128                                                                               │
│  pi loss (ep mean)  -0.869834                                                                              │
│  eta (ep mean)      8697887.894747                                                                         │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               2000 / 2903 (68.9%)                                                                    │
│  sim time           799.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.5466 rad                                                                            │
│  omega sat          -0.0130 rad/s                                                                          │
│  image smear        1.068 px                                                                               │
│  image quality      0.1153                                                                                 │
│  buffer             36835                                                                                  │
│  agent steps        36835                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       339084.374664                                                                          │
│  q loss (ep mean)   0.262654                                                                               │
│  pi loss (ep mean)  -0.869835                                                                              │
│  eta (ep mean)      10487306.635380                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               2100 / 2903 (72.3%)                                                                    │
│  sim time           839.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.2467 rad                                                                            │
│  omega sat          0.0010 rad/s                                                                           │
│  image smear        0.444 px                                                                               │
│  image quality      0.2988                                                                                 │
│  buffer             36935                                                                                  │
│  agent steps        36935                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       340350.821113                                                                          │
│  q loss (ep mean)   0.253534                                                                               │
│  pi loss (ep mean)  -0.869834                                                                              │
│  eta (ep mean)      12673305.682766                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               2200 / 2903 (75.8%)                                                                    │
│  sim time           879.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.5325 rad                                                                            │
│  omega sat          -0.0246 rad/s                                                                          │
│  image smear        1.569 px                                                                               │
│  image quality      0.0863                                                                                 │
│  buffer             37035                                                                                  │
│  agent steps        37035                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       341522.000135                                                                          │
│  q loss (ep mean)   0.244798                                                                               │
│  pi loss (ep mean)  -0.869836                                                                              │
│  eta (ep mean)      15340105.658993                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               2300 / 2903 (79.2%)                                                                    │
│  sim time           919.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.1444 rad                                                                            │
│  omega sat          0.0100 rad/s                                                                           │
│  image smear        0.138 px                                                                               │
│  image quality      0.5782                                                                                 │
│  buffer             37135                                                                                  │
│  agent steps        37135                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       342604.117721                                                                          │
│  q loss (ep mean)   0.243094                                                                               │
│  pi loss (ep mean)  -0.869835                                                                              │
│  eta (ep mean)      18590993.736462                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               2400 / 2903 (82.7%)                                                                    │
│  sim time           959.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.5599 rad                                                                            │
│  omega sat          -0.0361 rad/s                                                                          │
│  image smear        1.948 px                                                                               │
│  image quality      0.0762                                                                                 │
│  buffer             37235                                                                                  │
│  agent steps        37235                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       343660.001400                                                                          │
│  q loss (ep mean)   0.240383                                                                               │
│  pi loss (ep mean)  -0.869834                                                                              │
│  eta (ep mean)      22557747.211390                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               2500 / 2903 (86.1%)                                                                    │
│  sim time           999.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.0011 rad                                                                            │
│  omega sat          0.0216 rad/s                                                                           │
│  image smear        0.256 px                                                                               │
│  image quality      0.4245                                                                                 │
│  buffer             37335                                                                                  │
│  agent steps        37335                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       344591.027542                                                                          │
│  q loss (ep mean)   0.236487                                                                               │
│  pi loss (ep mean)  -0.869835                                                                              │
│  eta (ep mean)      27402077.867997                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               2600 / 2903 (89.6%)                                                                    │
│  sim time           1039.8 s                                                                               │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.6268 rad                                                                            │
│  omega sat          -0.0449 rad/s                                                                          │
│  image smear        2.143 px                                                                               │
│  image quality      0.0752                                                                                 │
│  buffer             37435                                                                                  │
│  agent steps        37435                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       345383.109327                                                                          │
│  q loss (ep mean)   0.242243                                                                               │
│  pi loss (ep mean)  -0.869835                                                                              │
│  eta (ep mean)      33316497.225135                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               2700 / 2903 (93.0%)                                                                    │
│  sim time           1079.7 s                                                                               │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.8163 rad                                                                            │
│  omega sat          0.0331 rad/s                                                                           │
│  image smear        0.667 px                                                                               │
│  image quality      0.2187                                                                                 │
│  buffer             37535                                                                                  │
│  agent steps        37535                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       346137.204792                                                                          │
│  q loss (ep mean)   0.236585                                                                               │
│  pi loss (ep mean)  -0.869835                                                                              │
│  eta (ep mean)      40544059.992636                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               2800 / 2903 (96.5%)                                                                    │
│  sim time           1119.7 s                                                                               │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.6914 rad                                                                            │
│  omega sat          -0.0370 rad/s                                                                          │
│  image smear        1.771 px                                                                               │
│  image quality      0.0939                                                                                 │
│  buffer             37635                                                                                  │
│  agent steps        37635                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       347037.001390                                                                          │
│  q loss (ep mean)   0.231889                                                                               │
│  pi loss (ep mean)  -0.869834                                                                              │
│  eta (ep mean)      49384804.127233                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               2900 / 2903 (99.9%)                                                                    │
│  sim time           1159.7 s                                                                               │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.5900 rad                                                                            │
│  omega sat          0.0446 rad/s                                                                           │
│  image smear        1.140 px                                                                               │
│  image quality      0.1367                                                                                 │
│  buffer             37735                                                                                  │
│  agent steps        37735                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       347600.276157                                                                          │
│  q loss (ep mean)   0.229468                                                                               │
│  pi loss (ep mean)  -0.869835                                                                              │
│  eta (ep mean)      60210941.715117                                                                        │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 3 / 5                                                                         │
│  step               2903 / 2903 (100.0%)                                                                   │
│  sim time           1160.9 s                                                                               │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.5333 rad                                                                            │
│  omega sat          0.0485 rad/s                                                                           │
│  image smear        1.329 px                                                                               │
│  image quality      0.1176                                                                                 │
│  buffer             37738                                                                                  │
│  agent steps        37738                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       347613.619998                                                                          │
│  q loss (ep mean)   0.229315                                                                               │
│  pi loss (ep mean)  -0.869835                                                                              │
│  eta (ep mean)      60570771.109623                                                                        │
│  status             episode done                                                                           │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 3: 100%|██████████| 2903/2903 [29:20<00:00,  1.65step/s, reward=0.000, total=0.0]

Train:  60%|██████    | 3/5 [1:27:00<58:17, 1748.58s/ep, kl=347614.0618, reward=0.0]

[run_serial] end mode=train steps=2903 total_reward=0.000000 avg_reward=0.000000

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 4 / 5                                                                         │
│  step               100 / 2903 (3.4%)                                                                      │
│  sim time           40.0 s                                                                                 │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.4594 rad                                                                            │
│  omega sat          -0.0256 rad/s                                                                          │
│  image smear        1.596 px                                                                               │
│  image quality      0.0851                                                                                 │
│  buffer             37838                                                                                  │
│  agent steps        37838                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       368158.119634                                                                          │
│  q loss (ep mean)   0.767443                                                                               │
│  pi loss (ep mean)  -0.869840                                                                              │
│  eta (ep mean)      461511297.939394                                                                       │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 4 / 5                                                                         │
│  step               200 / 2903 (6.9%)                                                                      │
│  sim time           80.0 s                                                                                 │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -2.0656 rad                                                                            │
│  omega sat          0.0113 rad/s                                                                           │
│  image smear        0.095 px                                                                               │
│  image quality      0.6660                                                                                 │
│  buffer             37938                                                                                  │
│  agent steps        37938                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       368693.392431                                                                          │
│  q loss (ep mean)   0.483820                                                                               │
│  pi loss (ep mean)  -0.869842                                                                              │
│  eta (ep mean)      521925348.180905                                                                       │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 4 / 5                                                                         │
│  step               300 / 2903 (10.3%)                                                                     │
│  sim time           120.0 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.4997 rad                                                                            │
│  omega sat          -0.0374 rad/s                                                                          │
│  image smear        1.972 px                                                                               │
│  image quality      0.0760                                                                                 │
│  buffer             38038                                                                                  │
│  agent steps        38038                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       368580.107651                                                                          │
│  q loss (ep mean)   0.372901                                                                               │
│  pi loss (ep mean)  -0.869842                                                                              │
│  eta (ep mean)      592847094.474916                                                                       │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 4 / 5                                                                         │
│  step               400 / 2903 (13.8%)                                                                     │
│  sim time           160.0 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.9175 rad                                                                            │
│  omega sat          0.0228 rad/s                                                                           │
│  image smear        0.302 px                                                                               │
│  image quality      0.3846                                                                                 │
│  buffer             38138                                                                                  │
│  agent steps        38138                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       368011.577616                                                                          │
│  q loss (ep mean)   0.298113                                                                               │
│  pi loss (ep mean)  -0.869838                                                                              │
│  eta (ep mean)      676172540.390978                                                                       │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 4 / 5                                                                         │
│  step               500 / 2903 (17.2%)                                                                     │
│  sim time           200.0 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.5702 rad                                                                            │
│  omega sat          -0.0446 rad/s                                                                          │
│  image smear        2.120 px                                                                               │
│  image quality      0.0765                                                                                 │
│  buffer             38238                                                                                  │
│  agent steps        38238                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       367409.622996                                                                          │
│  q loss (ep mean)   0.272549                                                                               │
│  pi loss (ep mean)  -0.869830                                                                              │
│  eta (ep mean)      774106301.498998                                                                       │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 4 / 5                                                                         │
│  step               600 / 2903 (20.7%)                                                                     │
│  sim time           239.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.7281 rad                                                                            │
│  omega sat          0.0344 rad/s                                                                           │
│  image smear        0.723 px                                                                               │
│  image quality      0.2048                                                                                 │
│  buffer             38338                                                                                  │
│  agent steps        38338                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       367127.925240                                                                          │
│  q loss (ep mean)   0.243573                                                                               │
│  pi loss (ep mean)  -0.869831                                                                              │
│  eta (ep mean)      889579107.739566                                                                       │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 4 / 5                                                                         │
│  step               700 / 2903 (24.1%)                                                                     │
│  sim time           279.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.6313 rad                                                                            │
│  omega sat          -0.0358 rad/s                                                                          │
│  image smear        1.731 px                                                                               │
│  image quality      0.0961                                                                                 │
│  buffer             38438                                                                                  │
│  agent steps        38438                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       366432.005231                                                                          │
│  q loss (ep mean)   0.221651                                                                               │
│  pi loss (ep mean)  -0.869836                                                                              │
│  eta (ep mean)      1026501045.241774                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 4 / 5                                                                         │
│  step               800 / 2903 (27.6%)                                                                     │
│  sim time           319.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.4972 rad                                                                            │
│  omega sat          0.0459 rad/s                                                                           │
│  image smear        1.217 px                                                                               │
│  image quality      0.1285                                                                                 │
│  buffer             38538                                                                                  │
│  agent steps        38538                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       366377.175532                                                                          │
│  q loss (ep mean)   0.255498                                                                               │
│  pi loss (ep mean)  -0.869840                                                                              │
│  eta (ep mean)      1188904367.058824                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 4 / 5                                                                         │
│  step               900 / 2903 (31.0%)                                                                     │
│  sim time           359.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.6529 rad                                                                            │
│  omega sat          -0.0244 rad/s                                                                          │
│  image smear        1.317 px                                                                               │
│  image quality      0.1248                                                                                 │
│  buffer             38638                                                                                  │
│  agent steps        38638                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       366568.088397                                                                          │
│  q loss (ep mean)   0.261268                                                                               │
│  pi loss (ep mean)  -0.869838                                                                              │
│  eta (ep mean)      1383165817.699666                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 4 / 5                                                                         │
│  step               1000 / 2903 (34.4%)                                                                    │
│  sim time           399.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.2401 rad                                                                            │
│  omega sat          0.0446 rad/s                                                                           │
│  image smear        1.364 px                                                                               │
│  image quality      0.1090                                                                                 │
│  buffer             38738                                                                                  │
│  agent steps        38738                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       366380.548236                                                                          │
│  q loss (ep mean)   0.266189                                                                               │
│  pi loss (ep mean)  -0.869841                                                                              │
│  eta (ep mean)      1614966514.002002                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 4 / 5                                                                         │
│  step               1100 / 2903 (37.9%)                                                                    │
│  sim time           439.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.6359 rad                                                                            │
│  omega sat          -0.0138 rad/s                                                                          │
│  image smear        0.951 px                                                                               │
│  image quality      0.1658                                                                                 │
│  buffer             38838                                                                                  │
│  agent steps        38838                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       366383.163814                                                                          │
│  q loss (ep mean)   0.364413                                                                               │
│  pi loss (ep mean)  -0.869841                                                                              │
│  eta (ep mean)      1892075650.067334                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 4 / 5                                                                         │
│  step               1200 / 2903 (41.3%)                                                                    │
│  sim time           479.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.0183 rad                                                                            │
│  omega sat          0.0331 rad/s                                                                           │
│  image smear        1.091 px                                                                               │
│  image quality      0.1233                                                                                 │
│  buffer             38938                                                                                  │
│  agent steps        38938                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       366165.237854                                                                          │
│  q loss (ep mean)   0.397418                                                                               │
│  pi loss (ep mean)  -0.869835                                                                              │
│  eta (ep mean)      2224010614.578815                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 4 / 5                                                                         │
│  step               1300 / 2903 (44.8%)                                                                    │
│  sim time           519.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.5808 rad                                                                            │
│  omega sat          -0.0046 rad/s                                                                          │
│  image smear        0.636 px                                                                               │
│  image quality      0.2293                                                                                 │
│  buffer             39038                                                                                  │
│  agent steps        39038                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       366478.802492                                                                          │
│  q loss (ep mean)   0.376415                                                                               │
│  pi loss (ep mean)  -0.869831                                                                              │
│  eta (ep mean)      2622726389.234796                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 4 / 5                                                                         │
│  step               1400 / 2903 (48.2%)                                                                    │
│  sim time           559.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.8381 rad                                                                            │
│  omega sat          0.0216 rad/s                                                                           │
│  image smear        0.701 px                                                                               │
│  image quality      0.1690                                                                                 │
│  buffer             39138                                                                                  │
│  agent steps        39138                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       366318.778234                                                                          │
│  q loss (ep mean)   0.363619                                                                               │
│  pi loss (ep mean)  -0.869834                                                                              │
│  eta (ep mean)      3102747976.714796                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 4 / 5                                                                         │
│  step               1500 / 2903 (51.7%)                                                                    │
│  sim time           599.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.5048 rad                                                                            │
│  omega sat          -0.0009 rad/s                                                                          │
│  image smear        0.512 px                                                                               │
│  image quality      0.2699                                                                                 │
│  buffer             39238                                                                                  │
│  agent steps        39238                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       366187.125104                                                                          │
│  q loss (ep mean)   0.353021                                                                               │
│  pi loss (ep mean)  -0.869832                                                                              │
│  eta (ep mean)      3680000461.854570                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 4 / 5                                                                         │
│  step               1600 / 2903 (55.1%)                                                                    │
│  sim time           639.9 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -0.6994 rad                                                                            │
│  omega sat          0.0100 rad/s                                                                           │
│  image smear        0.168 px                                                                               │
│  image quality      0.4483                                                                                 │
│  buffer             39338                                                                                  │
│  agent steps        39338                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       365968.713845                                                                          │
│  q loss (ep mean)   0.335291                                                                               │
│  pi loss (ep mean)  -0.869832                                                                              │
│  eta (ep mean)      4376119972.322701                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

╭──────────────────────────────────────────────── Live stats ────────────────────────────────────────────────╮
│  Parameter          Value                                                                                  │
│  episode            train ep 4 / 5                                                                         │
│  step               1700 / 2903 (58.6%)                                                                    │
│  sim time           679.8 s                                                                                │
│  step reward        0.0000                                                                                 │
│  episode return     0.00                                                                                   │
│  body z angle       -1.4210 rad                                                                            │
│  omega sat          0.0004 rad/s                                                                           │
│  image smear        0.466 px                                                                               │
│  image quality      0.2888                                                                                 │
│  buffer             39438                                                                                  │
│  agent steps        39438                                                                                  │
│  exploration        active (policy sample)                                                                 │
│  kl (ep mean)       366371.231037                                                                          │
│  q loss (ep mean)   0.320960                                                                               │
│  pi loss (ep mean)  -0.869831                                                                              │
│  eta (ep mean)      5218380941.090053                                                                      │
╰────────────────────────────────────────────────────────────────────────────────────────────────────────────╯

train ep 4:  61%|██████▏   | 1784/2903 [16:57<10:38,  1.75step/s, reward=0.000, total=0.0]

Train:  60%|██████    | 3/5 [1:43:58<1:09:18, 2079.34s/ep, kl=347614.0618, reward=0.0]

KeyboardInterrupt:

In [ ]:
tw.print_training_kpis(result)

In [ ]:
from utils.notebook.video import init_video_cell, play_saved_video

init_video_cell()

from utils.notebook.video import init_video_cell, play_saved_video

init_video_cell()
tw.display_training_artifacts(result)
video_path = result.artifact_paths["eval_best_video"]
if video_path.exists():
    play_saved_video(video_path)